### PR TITLE
Fix MacOS CI

### PR DESCRIPTION
**Pull request by domenukk**
This extends #830 with MacOS fixes

### CODE REVIEW

**Comment by domenukk** [comment]
This tries to address CI failures in #830

**Comment by domenukk** [comment]
Seems like it's no longer crashing, but the results are wrong...

Maybe related
https://github.com/rust-lang/libc/issues/414 ?

**Comment by domenukk** [comment]
I'm not sure if `addr_of!` is still needed, or if the crash was related to the false struct definition (?) but it's probably safer to leave it in

**Comment by mgeisler** [comment]
> I'm not sure if `addr_of!` is still needed, or if the crash was related to the false struct definition (?) but it's probably safer to leave it in

Yeah, not 100% sure about this myself. Let me merge it back into my branch and then I'll try both ways.

**Pull request merged**
