### PR TITLE
pt-BR: Updates/completes translations for ch 1-6

### PR DESCRIPTION
**Pull request by henrif75**
Part of #317

### CODE REVIEW

**Comment by rastringer** [comment]
Thanks @henrif75! Should be able to have a read through today

**Comment by rastringer** [comment]
Thanks again @henrif75. I wonder if we might go for 'arrays' for 'arrays' (vs 'matrizes'), perhaps mentioning ('vetores') in the first instance? If you're ok with that I could make the edits also. Then we can merge!

**Comment by henrif75** [comment]
@rastringer Sure, I'm fine with whatever convention we decide! TBH, I also agree we could keep "arrays" and tuples. My rationale for using "matrizes" was to keep consistency with the Rust Book: https://rust-br.github.io/rust-book-pt-br/ch03-02-data-types.html#o-tipo-matriz

**Review by rastringer — APPROVED** [review]

**Comment by rastringer** [comment]
Thanks for all your help with the translation, @henrif75! Merged

**Pull request merged**
