### PR TITLE
Check links are correct and fix those that aren't

### LINKED ISSUE #957: Check for broken links in CI
After #571 and #917 (thanks @eepeep and @djmitche!), it's becoming clear to me that we should check for broken links in our CI pipeline. The check should catch both 404 Not Found, but also know how to detect broken `#fragments` since those were the ones that became outdated in the past.

Since links can come and go at any moment, this test will not be super reliable — we might therefore want to only run it when something is merged into `main`. If it fails, people like me who are subscribed to the repository will get a mail and that should be enough for us to react.

### PR DESCRIPTION
**Pull request by adetaylor**
Fixes #957

### CODE REVIEW

**Review by qwandor — APPROVED** [review]

**Comment by mgeisler** [comment]
Thanks @adetaylor! I rebased this on top of `main` and there are a few new errors — in addition to the ones in the translations.

You could update the translations yourself, we could disable checking links there, or perhaps some other approach?

Testing this out it's nice: it caches the results and won't slow down the build (or `mdbook serve`).

**Comment by adetaylor** [comment]
> You could update the translations yourself, we could disable checking links there, or perhaps some other approach?

It actually looked to be a little fiddly to update the translations, since it appears that they do link to pages which may (or may not) actually exist when your browser is set to a different language. I think it possibly does need the actual translators to go through the mistakes.

I'm not quite sure what to do here. Disabling the link checking for translations seems bad, but perhaps as an interim step we should do that?

**Comment by randomPoison** [comment]
@adetaylor I'm in favor of disabling broken link checking for translations 👍 At least ensuring that the link is correct in the original English is an improvement of the current situation, and we can continue to fix broken links in the translations manually until we can figure out how to automatically valid links in translations.

Can you rebase this onto main and update it to only check the English slides?

**Comment by jond01** [comment]
Hi, please check out #2195 which does the same and more on top of the current main.

**Comment by jond01** [comment]
@mgeisler I think this can be closed now as #2195 has been merged.

**Comment by mgeisler** [comment]
Yes, let us close this. Thanks @adetaylor for starting this and thanks for pushing this over the finishing line, @jond01!

**Pull request closed without merging**
