### PR TITLE
uk: Day 4: morning

### PR DESCRIPTION
**Pull request by reta**
Day 4: morning

### CODE REVIEW

**Comment by reta** [comment]
@dyeroshenko the `msgid` change is legit (but check `Prevent unintended msgid changes / check-msgid-changes (pull_request)`) fails - there was indeed a change of the `msgid`  in main branch, I updated it and verified that the translation works as expected, I could probably revert it and do another pull request, please advice what you think is the best way to go, thank you!

**Comment by dyeroshenko** [comment]
> @dyeroshenko the `msgid` change is legit (but check `Prevent unintended msgid changes / check-msgid-changes (pull_request)` fails) - there was indeed a change of the `msgid` in main branch, I updated it and verified that the translation works as expected, I could probably revert it and do another pull request, please advice what you think is the best way to go, thank you!

I'm not sure of merging modified `msgif` won't break anything on mdbook level. @mgeisler, are we ok to modify the source `msgid` manually like [here](https://github.com/google/comprehensive-rust/pull/1910/commits/2b830f93d07587645e485d048390f51f4f6695b8#diff-79502c2528a8cf161a70b994b302a76c7508a610ec5e4bc71d1dc2c3122a8b1aR11082)? If not, there is no need to revert the whole translation but just to fix this message.

**Comment by reta** [comment]
> I'm not sure of merging modified `msgif` won't break anything on mdbook level. @mgeisler, are we ok to modify the source `msgid` manually like [here](https://github.com/google/comprehensive-rust/pull/1910/commits/2b830f93d07587645e485d048390f51f4f6695b8#diff-79502c2528a8cf161a70b994b302a76c7508a610ec5e4bc71d1dc2c3122a8b1aR11082)? If not, there is no need to revert the whole translation but just to fix this message.

thank you @dyeroshenko , for the record it is only a single occurrence: https://github.com/google/comprehensive-rust/pull/1910/files#diff-79502c2528a8cf161a70b994b302a76c7508a610ec5e4bc71d1dc2c3122a8b1aR11082

**Comment by reta** [comment]
@dyeroshenko my apologies for poking, it seems like @mgeisler is not available at the moment, I reverted the problematic `msgid` change (we could do that later), please take one more look, thank you.

**Review by dyeroshenko — APPROVED** [review]

**Comment by mgeisler** [comment]
> > I'm not sure of merging modified `msgif` won't break anything on mdbook level. @mgeisler, are we ok to modify the source `msgid` manually like [here](https://github.com/google/comprehensive-rust/pull/1910/commits/2b830f93d07587645e485d048390f51f4f6695b8#diff-79502c2528a8cf161a70b994b302a76c7508a610ec5e4bc71d1dc2c3122a8b1aR11082)? If not, there is no need to revert the whole translation but just to fix this message.
> 
> thank you @dyeroshenko , for the record it is only a single occurrence: https://github.com/google/comprehensive-rust/pull/1910/files#diff-79502c2528a8cf161a70b994b302a76c7508a610ec5e4bc71d1dc2c3122a8b1aR11082

Hey folks, sorry for the late reply... I'm behind on my notifications from the class.

The check is there to guide people to [either update `msgid` fields, or update the `msgstr` fields (not both)](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#refreshing-an-existing-translation). The `msgid` fields need to be in sync with the English content of the course at the date mentioned in the POT-Creation-Date, otherwise the translation won't be shown. So updating a single `msgid` field on its own is typically a mistake which will result in English text being rendered.

It's a harmless mistake: it will go away as soon as you refresh the translation again with `msgmerge`. That will ensure all `msgid` fields are up to date.

**Comment by mgeisler** [comment]
Sounds good! Thanks for all the hard work here, it's very impressive!

**Pull request merged**
