### PR TITLE
ko: normalize with mdbook-i18n-helpers 0.2.2

### PR DESCRIPTION
**Pull request by mgeisler**
Before, po/ko.po had these statistics:

    1323 translated messages, 231 fuzzy translations, 227 untranslated messages.

Afterwards, the statistics for po/ko.po is:

    1898 translated messages, 259 fuzzy translations, 310 untranslated messages.

The number of translated messages changed from 74% to 77%.

With this change, it becomes important to use the latest version of mdbook-i18n-helpers when viewing the translation locally. To update to the latest version, run

    cargo install mdbook-i18n-helpers

You will now be able to serve the translation locally.

Part of #330.

### CODE REVIEW

**Review by jiyongp — APPROVED** [review]
Thanks. This is good, but I think I have to rebase my ongoing branch. Not sure how much merge conflicts I will experience. ;)

**Comment by jiyongp** [comment]
> 

Nevermind. It was due to the msgmerge I did before I updated the translations.  I did msgmerge manually again, and the conflicts are manageable.

**Comment by jiyongp** [comment]
Thanks. I should have paid more attention to the notice. Yeah, after the normalize I see zero conflicts. There are more fuzzy translations; `* sentence1\n* sentence2\`  now is `sentence1` and `sentence2`, but this actually is good!

**Comment by mgeisler** [comment]
> Thanks. I should have paid more attention to the notice. Yeah, after the normalize I see zero conflicts. There are more fuzzy translations; `* sentence1\n* sentence2\` now is `sentence1` and `sentence2`, but this actually is good!

Excellent, I'm glad you like it! I hope the new system will give less churn and make things easier for everybody.

**Pull request merged**
