### PR TITLE
Fix duplicate Day 2 Afternoon exercise page

### PR DESCRIPTION
**Pull request by mgeisler**
Spotted by @gregpaton08 in #913.

### CODE REVIEW

**Comment by mgeisler** [comment]
This was found here: https://github.com/google/comprehensive-rust/commit/d3a90373b0007d7b90c940aef69e9a8b1eb98440#r125548839.

**Comment by mgeisler** [comment]
@fw-immunant, we'll probably merge the before you get online, but please skim it too to ensure I haven't forgotten anything.

**Comment by mgeisler** [comment]
Hmm, this isn't completely right:

> # Day 2: Morning Exercises
> We will look at implementing methods in two contexts:
> - Simple struct which tracks health statistics.
> - Multiple structs and enums for a drawing library.

The exercise named "A Simple GUI Library" is on Day 3 Morning.

**Review by fw-immunant — APPROVED** [review]
LGTM, thanks for catching this.

Edit: Ah, I see. Let me take a closer look and figure out what exactly should be where.

**Comment by mgeisler** [comment]
> Edit: Ah, I see. Let me take a closer look and figure out what exactly should be where.

Thanks a lot! I started looking, but got a bit lost myself :smile:

**Comment by djmitche** [comment]
FWIW there's already a subsequent reorg of this content planned, so I don't think it's worth spending too much time on this. Let's get it to a spot where it can be taught, and then focus on the v2.

**Comment by mgeisler** [comment]
Thanks for putting up #1136.

> FWIW there's already a subsequent reorg of this content planned, so I don't think it's worth spending too much time on this. Let's get it to a spot where it can be taught, and then focus on the v2.

Agreed. We'll close this and merge #1136 to get the loop fixed.

**Pull request closed without merging**
