### PR TITLE
Fix solution in Link Checker in Concurrency Morning exercises

### LINKED ISSUE #816: Concurrency morning solution does not contain a solution for Link Checker
Hi! 
Really enjoyed the course so far, I noticed something missing though so I'm opening an issue:

The [concurrency morning solutions file](https://github.com/google/comprehensive-rust/blob/main/src/exercises/concurrency/solutions-morning.md#L1) doesn't contain the solution for the [link checker task](https://github.com/google/comprehensive-rust/blob/main/src/exercises/concurrency/link-checker.md). I thought to check in [link-checker.rs](https://github.com/google/comprehensive-rust/blob/main/src/exercises/concurrency/link-checker.rs), but although it contains extra code it doesn't look like it solves the multi-threaded part of the problem

### PR DESCRIPTION
**Pull request by pwnall**
This change fixes the following issues with the current solution:

1. It is not listed on the "solutions" page.
2. It is not multi-threaded and does not use channels.

Fixes #816.

### CODE REVIEW

**Comment by pwnall** [comment]
@mgeisler This is a lot of code, and I'm pretty new at Rust. I won't be upset if you merge and change / rewrite, if that's easier than writing up a lot of feedback 😄

**Review by djmitche — APPROVED** [review]
This looks good! I added a few rustdoc comments. There are some interesting things to discuss here, such as using a Mutex to make a "mpmc" channel.

**Comment by pwnall** [comment]
@djmitche Thank you very much for the comment improvements!

In case it helps, I came up with the Arc+Mutex while trying to follow the exercise instructions at https://github.com/google/comprehensive-rust/blob/4413b6a28f6d0be5bf2d76564432015b072e2f5b/src/exercises/concurrency/link-checker.md?plain=1#L80-L81. In particular, I understood "send the URLs [...] to a channel" as asking me to figure out how to use a single mpsc::channel to coordinate between the "main" thread and the threads checking URLs.

I also considered the `crossbeam` crate, which offers "mpmc" channels. I thought that solution would be less compatible with the spirit of the exercise, because the instructions already include a list of crates for us to use.  By contrast, the proposal above ties in a few concepts introduced in the morning session.

I wrote my thoughts above hoping they help us come up with the best possible prompt text for future students.

**Comment by mgeisler** [comment]
> @mgeisler This is a lot of code, and I'm pretty new at Rust. I won't be upset if you merge and change / rewrite, if that's easier than writing up a lot of feedback smile

Thanks a lot for putting this up — people have been writing me asking for a solution :grimacing: Infact, we have #816 open for this :smile: 

Fun fact, to test this, I downloaded the code and tried to crawl https://google.github.io/comprehensive-rust/ instead — I was curious if we have broken links there! That soon resulted in

```
Got crawling error: bad http response: 429 Too Many Requests
```

errors and a bit later, I was blocked from posting this comment... luckily, the rate limit was lifted a few minutes later.

I noticed one thing:

```
Checking https://google.github.io/comprehensive-rust/print.html#assumptions
Checking https://google.github.io/comprehensive-rust/print.html#running-the-course
Checking https://google.github.io/comprehensive-rust/print.html#course-structure
Checking https://google.github.io/comprehensive-rust/print.html#deep-dives
```

It would be great to clean the URLs of any query string and anchor texts before inserting them into `visited_pages`.

**Comment by mgeisler** [comment]
Another thing I've noticed when doing this exercise in class: it's _super hard_ and I wish I had provided much more scaffolding for people to use. Your PR is already a great improvement, but I feel we should

1. Write comments above the functions we give to the students, and
2. Consider giving the major building blocks as well — with comments explaining what we expect people to fill in.

I'm an old-school web developer, but I've had people in my classes who've never done any web development whatsoever. HTTP status codes are foreign to them, HTML is foreign to them, URL fragments are foreign to them. Adding more scaffolding would probably help a lot there to make the exercise useful people from more backgrounds.

After this PR is merged, I would also like to include a diagram or two which shows the intended interaction between the crawler threads, the channels, and the main thread.

I've had people in my classes who took the old link extraction logic and ran that in a multi-threaded way — when that is a purely local and super fast operation. So we would need more detail explaining that it is the IO operations that are slow and which we seek to parallelize here.

**Review by 0951459527 — APPROVED** [review]

**Review by 0951459527 — COMMENTED** [review]
R Tao Channel

**Comment by pwnall** [comment]
@mgeisler I fully agree with your thoughts above! Would you be OK if I copied your thoughts (and my reply) into a separate Issue?

I see this PR as making a first step in what is hopefully the right direction. This PR brings the solution in line with the requirements outlined in the problem, with minimal scaffolding changes. I think that, once we agree that there are no obvious simplifications to the solution, we can conclude that the problem is too difficult. Once we're there, we can think of possible fixes.

I would be most interested in prototyping a scaffolding change where we give students a `spawn_crawler_threads` that works with a single crawler thread, and ask them to figure out how to support multiple crawler threads. I worry that this may make things too simple, but I figure I can iterate once I see what that looks like.

WDYT?

**Comment by jmpfar** [comment]
My extremely unedited solution with a single channel and no mutex
It's extremely full of .unwrap() and far from my proudest moment, but might be useful if you want to try adding that kind of solution
https://gist.github.com/jmpfar/4f6f0c4258037c0e4dda981a6d5dc6dc

**Comment by mgeisler** [comment]
> @mgeisler I fully agree with your thoughts above! Would you be OK if I copied your thoughts (and my reply) into a separate Issue?

Yes, definitely!

> I see this PR as making a first step in what is hopefully the right direction. This PR brings the solution in line with the requirements outlined in the problem, with minimal scaffolding changes. I think that, once we agree that there are no obvious simplifications to the solution, we can conclude that the problem is too difficult. Once we're there, we can think of possible fixes.

I completely agree, we should merge this now since it's a huge improvement on what we have.

> I would be most interested in prototyping a scaffolding change where we give students a `spawn_crawler_threads` that works with a single crawler thread, and ask them to figure out how to support multiple crawler threads. I worry that this may make things too simple, but I figure I can iterate once I see what that looks like.

My experience is that people find this to be a hard exercise — most find it too hard for the 30-40 minutes we normally have at this point in the course. I think less than 25% of the people in a class manage to write a working solution in that time.

**Comment by mgeisler** [comment]
> My extremely unedited solution with a single channel and no mutex It's extremely full of .unwrap() and far from my proudest moment, but might be useful if you want to try adding that kind of solution https://gist.github.com/jmpfar/4f6f0c4258037c0e4dda981a6d5dc6dc

Hi @jmpfar, thanks for posting this! Your solution is not bad: it delegates the I/O-heavy operations to new threads and does the CPU-intensive work in the main thread. Many people don't get to that stage.

A small problem with your solution is that you have an unbounded number of threads: if a page has 100 outgoing links, you spawn 100 threads. To solve that, you more or less have to create a multi-producer-multi-consumer abstraction: you need this to have a bounded number of threads read from a single channel.

**Comment by mgeisler** [comment]
> Anyway from my side I can attest this was the hardest exercise in the course (minus android and baremetal which I didn't do) and it took me significant time (but was fun all in all :)

Thanks, that matches my impression too. I'm glad you liked it despite it being hard :smile:  Perhaps it would be good to call it a "take home exercise" instead since it's really a small projects and not a real _exercise_ with a clear answer.

**Review by mgeisler — APPROVED** [review]
Let's get this merged since it's an excellent start for further updates. @fw-immunant has put up some PRs to restructure the course so he might have further input down the line.

**Comment by mgeisler** [comment]
Hi @pwnall, the build fails because a code block is not marked with `compile_fail`:

```
---- /tmp/mdbook-uKXC6H/exercises/concurrency/solutions-morning.md - Concurrency_Morning_Exercise::Link_Checker (line 108) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `reqwest`
  --> /tmp/mdbook-uKXC6H/exercises/concurrency/solutions-morning.md:126:5
```

When we run `mdbook test`, all code blocks are tested — but they're tested without dependencies. So we need to mark them as `compile_fail` if they depend on anything outside the standard library. @mauvealerts is looking to see if we can use mdbook-keeper (#175) to get more test coverage here.

**Comment by pwnall** [comment]
Thank you for decoding the error for me!

Let me figure out how to modify this chain to make the build green. I haven't updated a branch with someone else's commits before 😄

**Comment by pwnall** [comment]
@mgeisler Thank you again for the tips! The build is green now :)

**Comment by mgeisler** [comment]
> @mgeisler Thank you again for the tips! The build is green now :)

Yeah, looks good! Just for your information, we squash-merge all PRs in this repository. This makes it a bit easier for people since they can just add more and more commits to fix review comments. The commits all disappear from the main history when the branch is squash-merged into `main`. (But force-pushing like you did is also completely fine: that's the workflow you would use if you do a normal merge and want to preserve a nice history.)

**Comment by mgeisler** [comment]
> Thank you for decoding the error for me!

A small note: it feels terribly to have large code snippets that say `compile_fail` — how can we know that it still works? In this case we're saved by the fact that the code is included from an external `link-checker.rs` file which in turn is referenced by our [`Cargo.toml`](https://github.com/google/comprehensive-rust/blob/main/src/exercises/Cargo.toml#L39-L41) file. This means that we _do_ compile the link checker as part of our CI, but we do it outside of `mdbook test`.

**Pull request merged**
