### PR TITLE
Adding Romanian translation

### PR DESCRIPTION
**Pull request by RazvanSt**
Initial commit for the Romanian translation.

Part of #1451.

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @RazvanSt, thanks a lot for kicking this off! Let's merge this to get started and then we'll ask around to see if we can find another Romanian speaker to be a reviewer for future PRs.

**Review by mgeisler — APPROVED** [review]

**Comment by RazvanSt** [comment]
> Hi @RazvanSt, thanks a lot for kicking this off! Let's merge this to get started and then we'll ask around to see if we can find another Romanian speaker to be a reviewer for future PRs.
I've talked with some of my colleagues and they will join the effort. Thanks.

**Comment by mgeisler** [comment]
> > Hi @RazvanSt, thanks a lot for kicking this off! Let's merge this to get started and then we'll ask around to see if we can find another Romanian speaker to be a reviewer for future PRs.
> 
> I've talked with some of my colleagues and they will join the effort. Thanks.

Excellent! Let's merge this one now and then you and others can create smaller PRs to follow up. If you mark it as ready for review, then we can merge it right away.

**Comment by mgeisler** [comment]
@henrif75, can you work with @RazvanSt to find a 1-2 more Romanian speakers to review the followup PRs? @RazvanSt is a fellow Googler and said there might be some people in their team who can help here.

**Comment by RazvanSt** [comment]
@mihaidragospreda offered to help. He is also a fellow Googler.

**Pull request merged**
