### PR TITLE
Add Arc and Mutex to Arc/Mutex example

### PR DESCRIPTION
**Pull request by sudonym1**

### CODE REVIEW

**Comment by mgeisler** [comment]
Hey @sudonym1,

Thanks for the PR — I think you basically "solved" it by adding the code which I normally add when live-coding in class :smile:  That is, your changes are better suited for a speaker note (#53) than the main text.

**Comment by mgeisler** [comment]
@sudonym1 could you please recast this as an update to the speaker notes? Start by adding a `<details> ... </details>` block to the page and then explain things inside it. Tell the instructor what they should remember to show to the students.

**Review by mgeisler — CHANGES_REQUESTED** [review]
Please update the speaker notes instead.

**Comment by sudonym1** [comment]
Sure, I can do that.

**Comment by mgeisler** [comment]
> Sure, I can do that.

Awesome :smile: You simply need a `<details> ... </details>` element with some Markdown at the bottom of the page, that's it. There are a few examples of this in the course now: https://google.github.io/comprehensive-rust/welcome-day-1.html

**Comment by mgeisler** [comment]
Let me close this PR for now — please open another with updated speaker notes if you find time :smile:

**Pull request closed without merging**
