### PR TITLE
Move CSS files into `theme/` folder

### PR DESCRIPTION
**Pull request by hmn53**
Hi all,
This PR fixes https://github.com/google/comprehensive-rust/issues/1226:

* Moved CSS files to `theme/css`
* Moved speaker-notes.js to `theme/`
* Updated paths in book.toml

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @hmn53, thanks for this! I guess you got things working locally to verify that it looks okay after the move?

If so, could I get you to submit the CSS rules here in `theme/svgbob.css` to the upstream project? I think they belong there and I opened https://github.com/boozook/mdbook-svgbob/issues/22 a long time ago as a reminder to myself :smile:

**Comment by mgeisler** [comment]
I'm also a committer on the svgbob project, so I can help with the review there.

**Comment by hmn53** [comment]
Hey @mgeisler, I verified the changes locally and they're working fine.

For the issue https://github.com/boozook/mdbook-svgbob/issues/22, will we have the css rules inside the styles attribute in `svgbob.rs`?

**Comment by mgeisler** [comment]
> Hey @mgeisler, I verified the changes locally and they're working fine.

Thanks! It's all live now and it looks great!
 
> For the issue [boozook/mdbook-svgbob#22](https://github.com/boozook/mdbook-svgbob/issues/22), will we have the css rules inside the styles attribute in `svgbob.rs`?

I honestly don't know the project super well, but from a quick glance that looks correct. I don't see any other CSS in the project. Perhaps it comes from the svgbob library used? Let's discuss in the other bug! :slightly_smiling_face:

**Pull request merged**
