### PR TITLE
ja: Fix a typo in ja.po

### PR DESCRIPTION
**Pull request by ompugao**

### CODE REVIEW

**Comment by kantasv** [comment]
Hi, @ompugao-san, thanks for sending us an MR for our ja translation #652!
- As google-cla bot pointed out, Contributor License Agreement (CLA) is necessary for us to take a look at your MR.
- If you're willing to contribute to the project, please check [here](https://cla.developers.google.com/clas) for details :)

**Comment by ompugao** [comment]
Thanks for your guidance. I've signed the agreement.

**Review by kantasv — APPROVED** [review]
Hi, thanks for fixing this :) LGTM!

**Comment by kantasv** [comment]
@ompugao -san, thank you for sending an MR. Btw, Japanese translation project is still ongoing. If you want to help our JA translation project (and Japanese Rust community), please check the issue #652 ! Have a great day :)

**Pull request merged**
