### PR TITLE
Additional work on Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rastringer**
Code snippets days 1-4 are fixed, with comments in Br. Portuguese where appropriate. There will be the odd dangling error / mistranslation, which will be sorted as they are found. 
Generally all four days of the course are readable now to a decent standard. We will keep improving the grammar / vocab etc. 
Part of continuing work on issue #317.

### CODE REVIEW

**Comment by rastringer** [comment]
The tests don't like the the `C` code in section 33.5.1.1 Calling C with Bindgen. Is there a way around this please?
Run msgfmt --statistics -o /dev/null po/pt_BR.po
po/pt_BR.po:17662: keyword "typedef" unknown
po/pt_BR.po:17662:8: syntax error
po/pt_BR.po:17663: end-of-line within string
msgfmt: found 3 fatal errors
Error: Process completed with exit code 1.

**Comment by rastringer** [comment]
Please disregard comment re `C` above, realized there was a quotation marks missing! Fixed and tests passing.

**Comment by rastringer** [comment]
Excellent, thank you I'll download that one for the next endeavour.

**Comment by mgeisler** [comment]
> Excellent, thank you I'll download that one for the next endeavour.

Thanks, I see you got the strings normalized now, looks good :+1: 

You just let me know when you think we should merge this into the `main` branch.

> Generally all four days of the course are readable now to a decent standard.

It sounds like the translation is in an okay condition now? You and Hugo can still look it over after we merge it. I'll like to publish it next week if you two are comfortable with that?

**Comment by rastringer** [comment]
Yes definitely, I think we should merge then will do another review / check with Hugo before publication. Thanks for all your comms on this.

**Review by mgeisler — APPROVED** [review]
Thanks Robin!

**Pull request merged**
