### PR TITLE
ko: Update translation

### PR DESCRIPTION
**Pull request by jiyongp**
- Fixed Cell link (#1076)
- zh-TW: Translation for src/android/aidl/changing.md (#803)
- zh-CN: translate android/aidl/interface.md (#1078)
- zh-TW: Translate android/build-rules.md (#824)
- Iterate over array ref instead of array. (#1081)
- zh-CN: translate android/aidl/server.md && android/aidl/deploy.md  (#1086)
- zh-CN: translate error-handling (#968)
- zh-CN: translate android/build-rules/binary.md (#1072)
- zh-CN: translate android/build-rules/library.md (#1077)
- zh-TW: Translate async.md and async/async-await.md (#765)
- zh-CN: translate traits (#961)
- zh-CN: translate std (#962)
- Fix `dprint` comments in STYLE.md (#1092)
- de: normalize with mdbook-i18n-helpers 0.2.2 (#1114)
- it: normalize with mdbook-i18n-helpers 0.2.2 (#1105)
- pt-BR: normalize with mdbook-i18n-helpers 0.2.2 (#1104)
- zh-TW: normalize with mdbook-i18n-helpers 0.2.2 (#1100)
- ko: normalize with mdbook-i18n-helpers 0.2.2 (#1102)
- ko: rebase ongoing (incomplete) updates
- ko: fix fuzzy and missing translations in Intro and day 1
- ko: fix fuzzy and missing translations in day 2

### CODE REVIEW

**Comment by mgeisler** [comment]
This looks amazing! I just downloaded the branch and after running `msgmerge --update po/ko.po po/messages.pot` with a fresh `messages.pot` file, I only see a very small diff! Well done :star_struck:

**Comment by mgeisler** [comment]
> @mgeisler Update for day 1, 2, and 3 are done. I think we can merge this given that the three chapters are the most important ones. I will update the remaining chapters later.

That is super impressive, thanks! I think @jooyunghan should skim though this, if possible?

**Comment by jiyongp** [comment]
> > @mgeisler Update for day 1, 2, and 3 are done. I think we can merge this given that the three chapters are the most important ones. I will update the remaining chapters later.
> 
> That is super impressive, thanks! I think @jooyunghan should skim though this, if possible?

I think this can be merged without waiting for Jooyung's review. If he spots something later, he could submit a separate PR.

**Comment by jiyongp** [comment]
Ah, I anyway need a review vote from him.

**Review by mgeisler — APPROVED** [review]

**Comment by mgeisler** [comment]
> Ah, I anyway need a review vote from him.

I can give you the vote too :slightly_smiling_face: I would like us to find 2-3 more reviewers for Korean so we can have better coverage across the timezones and so we can avoid bottle-necks when people are on vacation etc.

**Pull request merged**
