### PR TITLE
Synced `de.po` with latest `messages.pot`

### PR DESCRIPTION
**Pull request by Throvn**
Updated the `de.po` file to include the latest english strings.
This should address the last comment of #285 by making it easier to do followup PRs with translations.

This PR is the result of running `msgmerge --update po/de.po po/messages.pot`.
No additional translations were added.

### CODE REVIEW

**Comment by ronaldfw** [comment]
Sorry for taking long to take a look at this. Could you sync to the latest version and run the command `msgmerge --update po/de.po po/messages.pot` again after creating messages.pot? When I do this, I'm seeing a lot of diffs between my result and your result.

For reference, I've run: 
```
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot"}}'  mdbook build -d po
msgmerge --update po/de.po po/messages.pot
```

and then
```
diff po/de.op <your-version-of-the-po-file>.po
```

Thanks!

**Comment by Throvn** [comment]
This is probably because of the commits that were done today.
I've updated the PR to include the latest changes now which should solve get rid of the differences.

**Review by ronaldfw — APPROVED** [review]
LGTM, thanks!

**Comment by ronaldfw** [comment]
(I've verified by running the commands myself.)

**Pull request merged**
