### PR TITLE
zh-Hans: Translation for src/basic-syntax/scopes-shadowing.md

### PR DESCRIPTION
**Pull request by Doris-Ge**
Part of https://github.com/google/comprehensive-rust/issues/324.

### CODE REVIEW

**Comment by mgeisler** [comment]
Hey @Doris-Ge, did this get merged via another PR?

@wnghl, perhaps you can fish out the translations here if they're not already merged.

**Comment by wnghl** [comment]
> Hey @Doris-Ge, did this get merged via another PR?
> 
> @wnghl, perhaps you can fish out the translations here if they're not already merged.

Hi @mgeisler, this is the PR that is currently using for this file #793

**Comment by mgeisler** [comment]
> Hi @mgeisler, this is the PR that is currently using for this file #793

Thanks, I was afraid the work would get lost, but I see you're on top of it! :smile:

**Comment by Doris-Ge** [comment]
Hi Martin, @wnghl is right. I closed this and opened https://github.com/google/comprehensive-rust/pull/793 for the file.

Sorry for the late response! I'm traveling these days, so I'm unable to reply instantly.

**Comment by mgeisler** [comment]
> Hi Martin, @wnghl is right. I closed this and opened #793 for the file.
> 
> Sorry for the late response! I'm traveling these days, so I'm unable to reply instantly.

All good, I'm super impressed with all the great work being done here!

**Review by HAMMERABA — APPROVED** [review]

**Comment by mgeisler** [comment]
Hey @HAMMERABA: please don't approve all these old pull requests. It triggers a mail to me and many others when you do.

**Pull request closed without merging**
