### PR TITLE
update file & translate to Chinese

### PR DESCRIPTION
**Pull request by SketchK**

### CODE REVIEW

**Comment by SketchK** [comment]
@henrif75 after review and merge your pr.
I try to continue translate the book to Chinese, this is my new PR.
It seems that I can't add myself as the reviewer, Could you give me a approve?
By the way, there are so many change, even if i just translate id 0 - id 500 sentences, 
I was using Poedit to edit .po file

**Comment by mgeisler** [comment]
> By the way, there are so many change, even if i just translate id 0 - id 500 sentences, Is that OK?
> I was using Poedit to edit .po file

I see many changes because Poedit has re-wrapped existing translations. Is it possible that you haven't [configured Poedit to stop reformatting the file?](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#Additional-Configuration-for-Poedit)

@nodmp, @wnghl, @superwhd, @anlunx, etc... I'm sure you had to deal with this as well?

**Comment by SketchK** [comment]
> > By the way, there are so many change, even if i just translate id 0 - id 500 sentences, Is that OK?
> > I was using Poedit to edit .po file
> 
> I see many changes because Poedit has re-wrapped existing translations. Is it possible that you haven't [configured Poedit to stop reformatting the file?](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#Additional-Configuration-for-Poedit)
> 
> @nodmp, @wnghl, @superwhd, @anlunx, etc... I'm sure you had to deal with this as well?

@mgeisler this is my Poedit setting, I think the current setup meets expectations
image

**Comment by SketchK** [comment]
@mgeisler @henrif75 
Anyone can help me ?

**Comment by henrif75** [comment]
> @mgeisler @henrif75 Anyone can help me ?

I'm taking a look.

**Comment by henrif75** [comment]
> > @mgeisler @henrif75 Anyone can help me ?
> 
> I'm taking a look.

The issue stems from using the normalizer before and the current file format is clunky. The msgmerge and POEdit kinda "fixed" that, but the diff is just huge.

My suggestion is send a PR just reformatting the PO file and all subsequent PRs will be much easier.
Let me do that right away, and then you can refresh this PR and see if the diff gets better.

**Comment by henrif75** [comment]
Sent #1337

**Comment by mgeisler** [comment]
> Sent #1337

Since we're seeing more of these problems, I think we should consider enforcing a standard format on the PO files. #1359 does that.

**Pull request closed without merging**
