### PR TITLE
Update translation file with v2 of book

### PR DESCRIPTION
**Pull request by moaminsharifi**
Message Ids synced with updated messages.po
Part of #671

### CODE REVIEW

**Review by DannyRavi — CHANGES_REQUESTED** [review]
before commit and push please use `dprint fmt po/fa.po` for code Formatting.

**Comment by moaminsharifi** [comment]
> before commit and push please use `dprint fmt po/fa.po` for code Formatting.
Thanks @DannyRavi for mention it.
Because of normalize issue I maked it draft. for now I am waiting for review of #1453 after it I will reopen it.

**Comment by mgeisler** [comment]
Hi @moaminsharifi and @DannyRavi, have you been able to fix the normalization issues?

If the merge/rebase gives you trouble, I would suggest just redoing the PR (since I assume it doesn't contain changes apart from extracting the new strings and then running `msgmerge`?).

**Comment by mgeisler** [comment]
Oh, I think I just duplicated this in #1751... please review either one so we can get things updated.

**Review by DannyRavi — APPROVED** [review]

**Comment by mgeisler** [comment]
Let us close this one, it got superseded by #1751.

**Pull request closed without merging**
