### PR TITLE
Revert "Saving the playground state in local storage (#1942)"

### LINKED ISSUE #2105: Most code snippets don't work anymore
As the title says, most code snippets don't work anymore

https://google.github.io/comprehensive-rust/concurrency/sync-exercises/solutions.html 
https://google.github.io/comprehensive-rust/iterators/exercise.html
https://google.github.io/comprehensive-rust/modules/exercise.html
etc...

### PR DESCRIPTION
**Pull request by djmitche**
This reverts commit e2cad7da8d85b3d7d783f064b6d4db5b6e7d9580.

Fixes #2105, #2104.

### CODE REVIEW

**Review by randomPoison — APPROVED** [review]
I ran into this in class today, happy to see that you already found the culprit and have a fix ready.

**Comment by mani-chand** [comment]
> @mani-chand, I'm sorry we had to revert the change.

Any bug?

**Comment by mani-chand** [comment]
> @mani-chand, I'm sorry we had to revert the change.

That's ok, I got it.

**Comment by djmitche** [comment]
The bugs were linked above -- it seems that exercises no longer appeared. If you hit "refresh" they would flash into existence, then disappear.

I don't know why this specifically occurred with exercises. My guess would be that it's because they are longer than most code sampls.

I wonder if we should give up on this -- it seems there are just too many corner cases with strange interactions. And when it fails, it dramatically interferes with ongoing instruction. What do you think?

**Comment by mani-chand** [comment]
> The bugs were linked above -- it seems that exercises no longer appeared. If you hit "refresh" they would flash into existence, then disappear.
> 

> I don't know why this specifically occurred with exercises. My guess would be that it's because they are longer than most code sampls.

I don't think it is because of longer codes but may be because of non-editable playground. 

> 
> I wonder if we should give up on this -- it seems there are just too many corner cases with strange interactions. And when it fails, it dramatically interferes with ongoing instruction. What do you think?

Yes, That's better.

**Comment by djmitche** [comment]
Sorry about that! We really appreciate your work on it. Some projects just turn out to be, if not impossible, at least impracatical. And I think this was one of them. Maybe we could have gotten this to work by forking ACE to handle persistent state or forking mdBook to generate a single-page app or something else -- but all of that is too great a cost for the desired result.

**Comment by mani-chand** [comment]
> Sorry about that! We really appreciate your work on it. Some projects just turn out to be, if not impossible, at least impracatical. And I think this was one of them. Maybe we could have gotten this to work by forking ACE to handle persistent state or forking mdBook to generate a single-page app or something else -- but all of that is too great a cost for the desired result.

There is nothing to say sorry, We did our best to make it work, Not everything work as expected. 

Second is that I got a job, It's been a hard time in job with high work pressure, I am getting less time to spend on this work.

**Comment by mgeisler** [comment]
Yeah, I agree with Dustin: thanks for the work you put into this, @mani-chand!

I think we should leave it as it is now. Perhaps we can revisit this one day if we get a proper testing framework for our JavaScript code — something that runs in a headless browser and which we can use to stress test things.

**Pull request merged**
