### PR TITLE
Publish Korean translation

### PR DESCRIPTION
**Pull request by mgeisler**
This adds the Korean translation to the list of published translations!

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @jiyongp and @keispace, as far as I understand, we can start publishing the Korean translation, right?

**Comment by jiyongp** [comment]
I wish we have a few more rounds before we publish it. I haven't finished proof-reading and revising it. See #302 for my progress.

**Comment by mgeisler** [comment]
> I wish we have a few more rounds before we publish it. I haven't finished proof-reading and revising it.

Okay, we can wait a bit — though we can also refine it as we get more PRs from the community :smile:

**Comment by jiyongp** [comment]
That's fair. Then let me finish proof-reading and revising the content for first day at least. Then we can publish for broader contribution.

**Comment by mgeisler** [comment]
Superseded by #428 which also updates the new language picker.

**Pull request closed without merging**
