### PR TITLE
vi: Welcome - Using Cargo translation

### PR DESCRIPTION
**Pull request by khoaxuantu**
Here is the translation of *Welcome to Comprehensive Rust: (2) Using Cargo.*

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @khoaxuantu, thanks for the PR!

@daivinhtran, will you be able to review this?

I'm not sure why the tests failed for unrelated languages, but perhaps something broke in our PDF publishing setup... I've restarted the tests and we'll then have to investigate more if they break again.

**Review by daivinhtran — APPROVED** [review]
@mgeisler yes, I was actually going to review this today.

**Comment by mgeisler** [comment]
Thanks @daivinhtran! I see that something is broken in the PDF generation:

```
  2024-04-03 17:00:00 [INFO] (mdbook::renderer): Invoking the "pandoc" renderer
  Warning:  Could not convert image /tmp/tex2pdf.-b8d581420691af04/9b1e09f6511f387768da72145790446bd7e7cf63.vs: Cannot load file
    Jpeg Invalid marker used
    PNG Invalid PNG file, signature broken
    Bitmap Invalid Bitmap magic identifier
    GIF Invalid Gif signature : error 
    HDR Invalid radiance file signature
    Tiff Invalid endian tag value
    TGA not enough bytes
  Error producing PDF.
  ! LaTeX Error: Unknown graphics extension: .vs.
  
  See the LaTeX manual or LaTeX Companion for explanation.
  Type  H <return>  for immediate help.
   ...                                              
                                                    
  l.168 ...1e09f6511f387768da72145790446bd7e7cf63.vs}}
  
  pandoc exited unsuccessfully
```

Let me create a bug for this so we can start merging these PRs.

**Comment by mgeisler** [comment]
Actually, #1911 is for that!

**Comment by mgeisler** [comment]
It's merged, thanks @daivinhtran for the review — and of course, thank you @khoaxuantu for writing the translation!

**Pull request merged**
