### PR TITLE
zh-Hans: Create `zh-Hans.po`

### PR DESCRIPTION
**Pull request by jzpin**
Start the translation of Chinese (Simplified). This is a freshly generated empty po file.

Part of #324.

### CODE REVIEW

**Comment by jzpin** [comment]
I have signed the CLA just now.

**Comment by mgeisler** [comment]
Thanks for getting this started @jzpin!

Based on https://github.com/google/comprehensive-rust/issues/324#issuecomment-1562327729, can I get you to rename the file to `zh-Hans.po`?

**Comment by jzpin** [comment]
> Thanks for getting this started @jzpin!
> 
> Based on [#324 (comment)](https://github.com/google/comprehensive-rust/issues/324#issuecomment-1562327729), can I get you to rename the file to `zh-Hans.po`?

Yes. Commit updated.

**Comment by mgeisler** [comment]
Excellent, thanks a lot! I'm excited to see this get started!

**Review by mgeisler — APPROVED** [review]

**Pull request merged**
