### PR TITLE
Add zh-hans translation

### PR DESCRIPTION
**Pull request by taotieren**
Add zh-hans translation

### CODE REVIEW

**Comment by taotieren** [comment]
Not yet translated, please merge later.

**Comment by mgeisler** [comment]
Hi @taotieren, thanks for the PR!

Can you please coordinate with @Hilbert-Yaa and @kiwiwarmnfuzzy from #324 for a Simplified Chinese translation?

**Comment by mgeisler** [comment]
> Not yet translated, please merge later.

Sure! I'll mark this as a "work in progress" for now so that we don't accidentally merge it :smile:

**Comment by taotieren** [comment]
> Hi @taotieren, there had been a few people working towards a simplified Chinese translation. Since it seems that your progress is still at the starting point of a machine-translated version, it would be more efficient if we can co-op on one translation. Please refer to #324

Now I have completed the first day, the second day and the last chapter on my side, and I still need to calibrate the third day and the fourth day. Will you do the latter part on your side?

**Comment by taotieren** [comment]
> Oh I see. Have you pushed the changes regarding the first day?

Are there other ways to communicate in real time (social software)?

**Comment by kiwiwarmnfuzzy** [comment]
Hi there - @taotieren: 

I think the Simplified Chinese translation of The Rust Programming Language book (https://github.com/KaiserY/trpl-zh-cn) is a good reference. By the way, if you have encountered a notable translation, feel free to add an entry in [this doc](https://docs.google.com/document/d/1Pxj1NUQGOuPrDb8FOW0qnOTpdPzjEQ6X5Z4ahbw_rvc/edit?usp=sharing). 

Cheers,
Jing

**Comment by mgeisler** [comment]
Hey @taotieren, I'll close this PR now. I would love to see you contribute towards the translation still, please see https://github.com/google/comprehensive-rust/issues/324#issuecomment-1562626220. There are plenty of files that need translation, so jump in :smile:

**Pull request closed without merging**
