### PR TITLE
Update course-structure.md

### PR DESCRIPTION
**Pull request by rickyclarkson**
Fixing a typo.

### CODE REVIEW

**Review by mgeisler — APPROVED** [review]

**Comment by mgeisler** [comment]
Hi @rickyclarkson, are you able to sign the CLA? Then we can merge it PR.

**Comment by keiichiw** [comment]
I wonder why this PR contains the big changes in ja.po by #1482. Do we need to merge the latest main branch into rickyclarkson:patch-1?

**Comment by djmitche** [comment]
That's a good question! @rickyclarkson do you want to push a clean version?

**Comment by rickyclarkson** [comment]
Closing, I'll create a new PR.

**Pull request closed without merging**
