### PR TITLE
ja: Normalize by running through mdbook-i18n-normalize 0.3.0

### PR DESCRIPTION
**Pull request by ternbusty**
Hello, JA translation team! (https://github.com/google/comprehensive-rust/issues/652) 

As part of #1460, I normalized ja.po using mdbook-i18n-normalize 0.3.0.

Steps taken:

1. Refreshed `po` file using the following command:

```
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot"}}' \
  mdbook build -d po
msgmerge --update po/ja.po po/messages.pot
```

2. Ran `mdbook-i18n-normalize`

I'm open to any feedback or suggestions. Thank you in advance!

### CODE REVIEW

**Comment by mgeisler** [comment]
> Steps taken:
> 
> 1. Refreshed `po` file using the following command:
> 
> ```
> MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot"}}' \
>   mdbook build -d po
> msgmerge --update po/ja.po po/messages.pot
> ```
> 
> 2. Ran `mdbook-i18n-normalize`

Hi @ternbusty, thanks for working on this!

You could not really know this from our documentation, but the two steps should be done in the opposite order. The reason is that `mdbook-i18n-normalize` known how to turn

```po
msgid ""
"fn main() {\n"
"  let x = 10; // foo\n"
"  let y = 20; // bar\n"
"}"
msgstr ""
"fn main() {\n"
"  let x = 10; // Japanese foo\n"
"  let y = 20; // Japanese bar\n"
"}"
```

into

```po
msgid "// foo\n"
msgstr "// Japanese foo\n"

msgid "// bar\n"
msgstr "// Japanese bar\n"
```

That is, it knows how to find the matching translations and thus how to _preserve_ the translations.

When you use `msgmerge` on the file, no such matching is done. The result is likely that the comments are un-translated in the `ja.po` file. That's a valid state, but some work is lost if the translations were translated before the `msgmerge`. It's quite subtle and you will need to find a code snippet with translated comments to see the difference.

In general, I would recommend against running `msgmerge` at the same time as you run `mdbook-i18n-helpers`. When you run them together, you end up with an extra-large PR, but if you just run the normalization tool by itself, then the PR diff should be more understandable.

**Comment by ternbusty** [comment]
Hi @mgeisler, Thank you for the detailed explanation!
I have reverted the above two commits and only performed normalization using mdbook-i18n-helpers without executing msgmerge.

**Comment by mgeisler** [comment]
> Hi @mgeisler, Thank you for the detailed explanation! I have reverted the above two commits and only performed normalization using mdbook-i18n-helpers without executing msgmerge.

Thanks, it now looks correct from a quick skim (I don't speak Japanese, but the diff looks like I would expect it to look).

One last thing... because of a small bug (https://github.com/google/mdbook-i18n-helpers/issues/117), you had to modify the POT-Creation-Date. It's great that you figured it out, but you should set the date to the original date +1 second instead.

The timestamp found there is used when we publish the translation. We use `git restore` to bring the Markdown files back to how they looked at the time in the POT-Creation-Date. This allows us to "freeze" the translation in time and give people a stable ground to work on.

This also means that when you advance the time to "now", the next publication will have lots of untranslated strings. You should be able to see this if you download the [comprehensive-rust-ja](https://github.com/google/comprehensive-rust/suites/18300736434/artifacts/1058503709) artifact from the bottom of the [Test](https://github.com/google/comprehensive-rust/actions/runs/6911382975) page.

Until we fix https://github.com/google/mdbook-i18n-helpers/issues/117 and make a new release, we will have this little issue.

**Comment by ternbusty** [comment]
Thank you for your guidance. I've adjusted the POT-Creation-Date to be the original date +1 second.

**Comment by mgeisler** [comment]
@kantasv, @keiichiw, and @chikoski, I think this looks good from a technical point of view!

**Pull request merged**
