### PR TITLE
Add support for right-to-left languages

### LINKED ISSUE #1164: Test new `mdbook` right-to-left rendering
With https://github.com/rust-lang/mdBook/pull/1641 merged, we can now test out the right-to-left rendering.

We should

1. Update `mdbook` to use a version from Git (edit `.github/workflows/install-mdbook/action.yml`).
2. Enable publication for #671.
3. Ensure that Persian is rendered nicely (ask @mbpouri and @DannyRavi for input).

### PR DESCRIPTION
**Pull request by mgeisler**
This updates our `mdbook` version to the latest version in Git. I copied the `index.hbs` file from that version and back-ported our changes into it. I checked English and Danish locally and they both look fine.

The new version has support for right-to-left languages: https://github.com/rust-lang/mdBook/pull/1641.

We have an in-progress Persian translation. Download the `fa.zip` artifact after building the PR to check how it looks. I checked Persian locally and it looks mirrored like I expect (but we will need someone who can read Persian to actually verify this).

Fixes #1164.

### CODE REVIEW

**Comment by mgeisler** [comment]
The tests are done. @mbpouri and @DannyRavi, can you please take a look at [`comprehensive-rust-fa.zip`](https://github.com/google/comprehensive-rust/suites/15802787128/artifacts/901813619) and let us know how it looks?

**Review by DannyRavi — COMMENTED** [review]
According to the implementation I had from comprehensive-rust-fa.zip, the RTL result is good, and according to the experience of RTLs on other platforms, when each line of text starts with an LTR letter, an error occurs in the text.
Also, please check [rust-lang/mdBook#1164](https://github.com/google/comprehensive-rust/issues/1164)

**Comment by mgeisler** [comment]
> According to the implementation I had from comprehensive-rust-fa.zip, the RTL result is good, and according to the experience of RTLs on other platforms, when each line of text starts with an LTR letter, an error occurs in the text. Also, please check [rust-lang/mdBook#1164](https://github.com/google/comprehensive-rust/issues/1164)

Thanks @DannyRavi! I think we should merge this then and we'll let you and others figure out any small details in the coming weeks.

**Comment by mgeisler** [comment]
@DannyRavi, I've invited you to collaborate on the repository — this should let you add a review on this PR so I can merge it!

**Review by henrif75 — APPROVED** [review]

**Comment by mgeisler** [comment]
This is now published, see: https://google.github.io/comprehensive-rust/fa/ :rocket:

**Pull request merged**
