### PR TITLE
Add speaker notes to stack and heap pages 

### PR DESCRIPTION
**Pull request by brandonpollack23**
Added stuff in the memory management chapter

### CODE REVIEW

**Comment by mgeisler** [comment]
Thanks! I'll fixup the capitalization of Rust before merging this later today.

**Comment by brandonpollack23** [comment]
Thanks for your tolerance, I'll try to be more careful next time

**Comment by fbornhofen** [comment]
Made some minor capitalization changes in two files, hoping that this is what Martin had in mind.

Thanks for the PR!

**Comment by mgeisler** [comment]
> Thanks for your tolerance, I'll try to be more careful next time

All good, keep sending us PRs! I'm very happy to do small fixes if you do the more complicated task of writing good notes :smile:

**Pull request merged**
