### PR TITLE
ja: Chapter 0

### PR DESCRIPTION
**Pull request by CoinEZ-JPN**
- `mdbook serve` does NOT reflect translations in the following areas in both localhost and prod
Screenshot 2023-05-30 at 20 27 23
- same behavior as above observed in prod for Brazilian and Korean
- minor edits to table of contents for consistency in first commit

Part of #652.

### CODE REVIEW

**Comment by mgeisler** [comment]
> * same behavior as above observed in prod for Brazilian and Korean

Strange, but I can reproduce this as well! Let me open a dedicated issue for this.

**Review by keiichiw — APPROVED** [review]
Thank you for the PR! LGTM for the translation. 

I guess we can ignore the `mdbook serve` issue for now and merge this PR, as @mgeisler will file another issue.

**Comment by mgeisler** [comment]
> > > * same behavior as above observed in prod for Brazilian and Korean
> > 
> > 
> > Strange, but I can reproduce this as well! Let me open a dedicated issue for this.
> 
> ok, thank you

Ah, I tested this again!

The problem is that the paragraph has changed in a subtle way in the source material in #668. This means that the PO file is slightly outdated.

You have to refresh the `ja.po` file to incorporate the latest changes. You [use `msgmerge` to do this](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#updating-an-existing-translation). It will match the old English text with the new paragraph and re-use your translation. However, the whole entry is marked as "fuzzy", which means that someone (you) should proof-read it before removing the fuzzy marker.

This step is a bit annoying: `msgmerge` will cause a lot of diffs since it likely formats the file differently compared to your PO editor and compared to the format used by `mdbook-xgetttext`. Someone (probably me) needs to add some normalization code to the `mdbook-i18n-helpers` so that we can have more stable output from these tools.

For now, I would just ignore this and keep translating the PO file. You can decide when to synchronize the `ja.po` file when you feel there has been [enough changes to `src/`](https://github.com/google/comprehensive-rust/commits/main/src) to make it worth the trouble.

**Comment by mgeisler** [comment]
@CoinEZ-JPN are you able to merge this PR now that it has been approved? I'm not actually sure if you can do that without having write access. If not, one of @keiichiw or @chikoski should merge it.

**Comment by CoinEZ-JPN** [comment]
@mgeisler sorry, it doesn't look like I can

s/s↓
Screenshot 2023-06-03 at 10 41 16

**Comment by mgeisler** [comment]
> @mgeisler sorry, it doesn't look like I can
> 
> s/s↓ Screenshot 2023-06-03 at 10 41 16

Thanks for testing, I'll merge it now!

**Pull request merged**
