### PR TITLE
ro: Refresh Romanian translation

### PR DESCRIPTION
**Pull request by RazvanSt**
Some more updates to the translation.

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @RazvanSt, thanks for the update! Running

```
gh pr diff 1991 | bat -l patch
```

shows me that you're re-introducing line numbers on the source lines:

```patch
-#: src/SUMMARY.md
+#: src/SUMMARY.md:18 src/SUMMARY.md:47 src/SUMMARY.md:76 src/SUMMARY.md:103
+#: src/SUMMARY.md:129 src/SUMMARY.md:149 src/SUMMARY.md:167 src/SUMMARY.md:190
+#: src/SUMMARY.md:213 src/SUMMARY.md:262 src/SUMMARY.md:304 src/SUMMARY.md:355
 msgid "Welcome"
 msgstr "Bine ați venit"
 
-#: src/SUMMARY.md src/hello-world.md src/hello-world/hello-world.md
-#, fuzzy
+#: src/SUMMARY.md:19 src/SUMMARY.md:24 src/hello-world.md:1
+#: src/types-and-values/hello-world.md:1
 msgid "Hello, World"
-msgstr "Bună lume!"
+msgstr "Bună lume"
```

This is because you haven't set the "granularity" when extracting strings. See [TRANSLATIONS.md](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md). Perhaps your `mdbook-i18n-helpers` are old, if the setting doesn't seem to have an effect.

**Comment by RazvanSt** [comment]
Thank you.

I am trying to push from an older branch. I'll do a rebase and try to fix
the issues.

**Comment by RazvanSt** [comment]
Should be fixed now, but the format still fails.

**Comment by mgeisler** [comment]
> Should be fixed now, 

I still see the line numbers on the source lines:

```patch
diff --git a/po/ro.po b/po/ro.po
index 33b56d8efca..edf6bb20bbb 100644
--- a/po/ro.po
+++ b/po/ro.po
@@ -1,8 +1,8 @@
 msgid ""
 msgstr ""
 "Project-Id-Version: Comprehensive Rust 🦀\n"
-"POT-Creation-Date: 2024-01-24T13:24:49+01:00\n"
-"PO-Revision-Date: 2023-11-07 15:51+0200\n"
+"POT-Creation-Date: 2024-04-15T17:42:59+03:00\n"
+"PO-Revision-Date: 2024-04-05 08:52+0300\n"
 "Last-Translator: Razvan Stefanescu <rstefanescu@google.com>\n"
 "Language-Team: Romanian <translation-team-ro@lists.sourceforge.net>\n"
 "Language: ro\n"
@@ -11,1268 +11,1286 @@ msgstr ""
 "Content-Transfer-Encoding: 8bit\n"
 "Plural-Forms: nplurals=3; plural=n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < "
 "20)) ? 1 : 2;\n"
-"X-Generator: Poedit 3.4.1\n"
+"X-Generator: Poedit 3.4.2\n"
 
-#: src/SUMMARY.md src/index.md
+#: src/SUMMARY.md:3 src/index.md:1
 msgid "Welcome to Comprehensive Rust 🦀"
 msgstr "Bine ați venit la Comprehensive Rust 🦀 (ghidul complet pentu Rust)"
```

> but the format still fails.

Try deleting the old entries that start with `#~`:

```
@@ -38324,8 +42824,8 @@ msgstr ""
 #~ "        let Some(request_segment) = request_segments.next() else {\n"
 #~ "            return false;\n"
 #~ "        };\n"
-#~ "        if request_segment != prefix_segment && prefix_segment ! = "
-#~ "\"*\" {\n"
+#~ "        if request_segment != prefix_segment && prefix_segment ! = \"*\" "
+#~ "{\n"
 #~ "            return false;\n"
 #~ "        }\n"
 #~ "    }\n"
```

They represent inactive translations.

**Comment by RazvanSt** [comment]
Phew. Fixed. I used to "Translation/Purge Deleted Translations" in Poedit to remove stalled translations and fixed to left/right single/double quotes.

**Comment by mgeisler** [comment]
@RazvanSt, do you know someone who could review your PRs? I just need someone to read through them and click the review button. It would be great if you know a Romanian Rust community?

**Comment by mgeisler** [comment]
> ```diff
> -#: src/SUMMARY.md src/index.md
> +#: src/SUMMARY.md:3 src/index.md:1
>  msgid "Welcome to Comprehensive Rust 🦀"
>  msgstr "Bine ați venit la Comprehensive Rust 🦀 (ghidul complet pentu Rust)"
> ```

This is still a problem: please make sure to use the `"granularity": 0` setting when running `mdbook-xgettext`.

**Comment by RazvanSt** [comment]
Hello,

Grrrr, this email thread got lost among others and forgot to reply to it.

Unfortunately I do not know anybody in the romanian Rust community, but
I'll ask one of my colleagues to take a look.

Regards,
Razvan

**Comment by RazvanSt** [comment]
I think there is a problem with the creation/update of the messages.pot
file:


*$ mdbook --versionmdbook v0.4.36*
*$ MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity":
0}}' mdbook build -d po*
*$ MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot-g1",
"granularity": 1}}' mdbook build -d po*




*$ diff po/messages.pot po/messages.pot-g15c5< "POT-Creation-Date:
2024-05-09T14:33:28+03:00\n"---> "POT-Creation-Date:
2024-05-09T14:34:25+03:00\n"*

There is no difference in the messages.pot file when using granularity 0 or
1. Tested with mdbook v0.4.36 and v0.4.37. Am I missing something?

Regards,
Razvan

**Comment by mgeisler** [comment]
> There is no difference in the messages.pot file when using granularity 0 or 1. Tested with mdbook v0.4.36 and v0.4.37. Am I missing something?

Strange, but I think I know what it is: you probably need to update `mdbook-i18n-helpers`:

```
cargo install mdbook-i18n-helpers
```

You should have version 0.3.2.

The use of `mdbook build -d po*` looks a bit odd. Just use `mdbook build -d po` to put the file into the `po/` directory.

**Comment by mgeisler** [comment]
> Unfortunately I do not know anybody in the romanian Rust community, but I'll ask one of my colleagues to take a look.

Thank you, that will be great! You can also try asking on various forums — I've done that myself in the past.

**Comment by mgeisler** [comment]
It looks good now, let's merge this! Thanks!

Until the translation is ~50% done, I would recommend freshing it only every ~3 months or so.

**Review by mgeisler — APPROVED** [review]

**Pull request merged**
