### PR TITLE
Simplify the solution to prefix matching

### PR DESCRIPTION
**Pull request by zhouwfang**

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @zhouwfang, thanks a lot! This looks much better indeed :smile: 

I would be happy to merge this, we just need the CLA to be signed.

**Comment by zhouwfang** [comment]
Hi @mgeisler, CLA has been signed. Thanks.

**Comment by zhouwfang** [comment]
Hi @mgeisler, It should be all set now. Thanks.

**Comment by mgeisler** [comment]
Thanks! Could I also get you to add a few comments to explain the solution? In particular the trick with turning the elements into `Option` so we can detect when the prefix iterator ends.

**Pull request merged**
