### PR TITLE
Fix typo android/interoperability/cpp.md

### PR DESCRIPTION
**Pull request by panpilkarz**
Fix double parenthesis typo in `SUMMARY.md`

### CODE REVIEW

**Review by mgeisler — APPROVED** [review]
Thanks for spotting this!

**Comment by mgeisler** [comment]
Hi @panpilkarz, if you can sign the CLA, then we can merge this.

**Comment by panpilkarz** [comment]
Hi @mgeisler I keep trying but no luck. 

https://cla.developers.google.com/

**Comment by mgeisler** [comment]
> Hi @mgeisler I keep trying but no luck.
> 
> image

Oh, that's strange! This happens on https://cla.developers.google.com/? It's possible that it has a problem — if so, I hope it will be fixed in a day or two! I suggest trying again later and then just ping me here when it works.

**Comment by mgeisler** [comment]
Hi @panpilkarz, could you please try the CLA process again? I hope whatever problem the server had would be fixed by now.

**Comment by panpilkarz** [comment]
Hi @mgeisler it is sorted out now. Happy merging!

**Comment by mgeisler** [comment]
> Hi @mgeisler it is sorted out now. Happy merging!

Yay, thanks for not giving up!

**Pull request merged**
