### PR TITLE
uk: Cleaning up Ukrainian cloud-translate translations (intro section)

### PR DESCRIPTION
**Pull request by reta**
Covers the intro section (part of https://github.com/google/comprehensive-rust/issues/836)

### CODE REVIEW

**Comment by reta** [comment]
> Hi @reta, the failing format check can be fixed with `dprint fmt` after installing the tools mentioned in [CONTRIBUTING.md](https://github.com/google/comprehensive-rust/blob/main/CONTRIBUTING.md).

Thanks a lot @mgeisler , will do that

**Comment by reta** [comment]
```
 dprint.exe fmt  -L debug

...
[DEBUG] No change: C:\Users\<redacted>\comprehensive-rust\po\uk.po
...

```

**Comment by mgeisler** [comment]
> ```
>  dprint.exe fmt  -L debug
> 
> ...
> [DEBUG] No change: C:\Users\<redacted>\comprehensive-rust\po\uk.po
> ...
> ```

The format check is happy now! :smile:

**Comment by reta** [comment]
> The format check is happy now! 😄

Thanks a lot @mgeisler ! I suspect the translation may take some time, I will be pushing the changes here periodically (making sure the formatter is happy) and I don't want to distract you every time there is a new revision, do you prefer me to ping you when pull request is ready (non-draft anymore)? Thank you!

**Comment by mgeisler** [comment]
> > The format check is happy now! 😄
> 
> Thanks a lot @mgeisler ! I suspect the translation may take some time, I will be pushing the changes here periodically (making sure the formatter is happy) and I don't want to distract you every time there is a new revision, do you prefer me to ping you when pull request is ready (non-draft anymore)? Thank you!

I won't be able to review the Ukrainian, I can only comment on the technical aspects :slightly_smiling_face: But small PRs are much better than large PRs. So ideally, @dyeroshenko should come take a look at the PR so it can be merged.

Therefore, mark it as non-wip as soon as you're happy with what you've got and then we should get it merged. If you know 1-2 people more who are interested in being your reviewers, then let us know and we can get them added to the repository.

Ultimately, the translations only work if people self-organize, so you have pretty free hands here.

**Comment by reta** [comment]
Finished the `intro` section up to Day 1, @dyeroshenko could you please help me out here? (I think translating in steps would be better and also simpler to review / divide), thank you

**Review by dyeroshenko — APPROVED** [review]

**Pull request merged**
