### PR TITLE
Update points-polygons.rs Polygon::length solution to use iterators

### PR DESCRIPTION
**Pull request by edemir**
Update points-polygons.rs Polygon::length solution to use iterators for pairwise distance calculation

### CODE REVIEW

**Review by mgeisler — CHANGES_REQUESTED** [review]
Hi @edemir, thanks for the elegant solution!

Since this exercise is for beginners, I would suggest we keep the simpler solution as the default. Your solution could go into a comment instead as an alternative.

**Comment by mgeisler** [comment]
Hi @edemir, thanks for updating the code to use a comment — is there a particular reason you closed the PR?

**Comment by edemir** [comment]
Hi @mgeisler I tried to squash two commits and bungled it up. Created a fresh pull requests here: https://github.com/google/comprehensive-rust/pull/950

**Comment by mgeisler** [comment]
> Hi @mgeisler I tried to squash two commits and bungled it up. Created a fresh pull requests here: #950

Okay, thanks for putting up the new PR! Just so you know, we squash-merge all PRs in this repository so you don't have to be very careful with the commit history in a PR. We do this to lower the barrier to entry: we only need to ensure the PRs have a nice title since that's what will be preserved in the history.

**Pull request closed without merging**
