### PR TITLE
Update welcome-day-1.md

### PR DESCRIPTION
**Pull request by karthicktam**

### CODE REVIEW

**Review by mgeisler — APPROVED** [review]
Thanks a lot, that sounds much better indeed :smile:

**Comment by mgeisler** [comment]
If you can fix the failing CLA check, then we can merge this.

**Comment by karthicktam** [comment]
> If you can fix the failing CLA check, then we can merge this.
CLA issue have been fixed thanks for accepting the pull request

**Comment by mgeisler** [comment]
Thanks a lot!

**Pull request merged**
