### PR TITLE
zh-CN: Publishes CR2 translation

### PR DESCRIPTION
**Pull request by henrif75**
This PR simply merges the consolidated `zh-CN.po` file into the `main` branch, publishing the translation of the CR2.
All commits were reviewed, so this won't need to be reviewed prior to be pushed.

### CODE REVIEW

**Comment by henrif75** [comment]
Hi reviewers,
I was checking the `zh-CN.po` file, and for some reason there's still a lot of fuzzy entries. I wa wondering if some of you could take a look and clean that up a little?

**Comment by henrif75** [comment]
Hi @mgeisler ,
I'm thinking on pushing this refreshed translation regardless of the fuzzy content and then ask the community to improve it afterwards. WDYT?

**Comment by mgeisler** [comment]
> Hi @mgeisler , I'm thinking on pushing this refreshed translation regardless of the fuzzy content and then ask the community to improve it afterwards. WDYT?

I think that is fine. In general, you and I cannot "finish" the translations — since we don't speak most of the languages :smile:  So a translation can only become as good as the community around it makes it.

**Comment by mgeisler** [comment]
Oh, and the community around the Simplified Chinese translation has been amazing! So I'm sure people will come and help out when they see the English text here and there in the translation.

**Comment by henrif75** [comment]
I'm sending a clean PR and closing this one.

**Review by deavid — APPROVED** [review]

**Pull request closed without merging**
