### PR TITLE
Misc doc fixes

### PR DESCRIPTION
**Pull request by kianmeng**
List of changes:
- fix typos found via `codespell -S target -L crate`
- ignore Cargo.lock
- hide dollar signs used before commands without output for easier copy and paste in Github

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @kianmeng, thanks a lot for this! I would love to land the typo fixes (of course!).

I'm less sure about removing the `$` from the shell command lines. They become important for the part about Android where I sometimes show the output: https://google.github.io/comprehensive-rust/android/build-rules/binary.html.

Can you rebase your branch on top of `main` and take out the `$` changes to start with? Ideally, `mdbook` should let us copy just the commands and ignore the `$`.

**Comment by kianmeng** [comment]
@mgeisler Done. Please check again.

**Comment by mgeisler** [comment]
Thanks a lot!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
