### PR TITLE
zh-CN: Restores PO file structure format

### PR DESCRIPTION
**Pull request by henrif75**
This will restore the regular structure format of the PO file (line breaks and wrap) and does not change the content itself. Part of #324

### CODE REVIEW

**Review by SketchK — APPROVED** [review]

**Comment by SketchK** [comment]
Hi, @henrif75 I check the restores PO file structure format, It seem ok!
but [the publish part ](https://github.com/google/comprehensive-rust/actions/runs/6477128372/job/17587098322)seems times out?

**Comment by henrif75** [comment]
> Hi, @henrif75 I check the restores PO file structure format, It seem ok! but [the publish part ](https://github.com/google/comprehensive-rust/actions/runs/6477128372/job/17587098322)seems times out?

@mgeisler I tried to re-run and I'm getting the same problem, would you know what's wrong with the action?

**Comment by henrif75** [comment]
> > Hi, @henrif75 I check the restores PO file structure format, It seem ok! but [the publish part ](https://github.com/google/comprehensive-rust/actions/runs/6477128372/job/17587098322)seems times out?
> 
> @mgeisler I tried to re-run and I'm getting the same problem, would you know what's wrong with the action?

I guess it was a transient problem, the workflow worked correctly now.

**Comment by mgeisler** [comment]
> > > Hi, @henrif75 I check the restores PO file structure format, It seem ok! but [the publish part ](https://github.com/google/comprehensive-rust/actions/runs/6477128372/job/17587098322)seems times out?
> > 
> > 
> > @mgeisler I tried to re-run and I'm getting the same problem, would you know what's wrong with the action?
> 
> I guess it was a transient problem, the workflow worked correctly now.

Yeah, I don't know why it would timeout — luckily it seems fine now.

**Pull request merged**
