### PR TITLE
fa:  Adding Persian translations to side bar items

### PR DESCRIPTION
**Pull request by moaminsharifi**
Part of #671
**Summary of changes:** 
- persian version of book messages synced to orginal book
- Translate sidebar menu
*for making easier for Reviewers, I just translate and double check until `# src/SUMMARY.md:333` part*

Suggestions:
1- Convert "منابع" to "حافظه" for Rust Memory Management
```
#: src/SUMMARY.md:88
msgid "Rust Memory Management"
msgstr "مدیریت منابع Rust"
```
In the Persian Computer community when we call "Memory" is "حافظه"

Plus, in other places translted to "حافظه"
```
#: src/SUMMARY.md:85 src/memory-management/manual.md:1
msgid "Manual Memory Management"
msgstr "مدیریت دستی حافظه"
```

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @moaminsharifi, in case you didn't notice: `msgmerge` moved a bunch of translations to a kind of "paper bin" at the end of the PO file:

```patch
@@ -21004,3 +19937,150 @@ msgid ""
 "}\n"
 "```"
 msgstr ""
+
+#~ msgid "Comparison"
+#~ msgstr "مقایسه"

```

You should delete them when you think they're no longer useful — the code blocks found there are no longer useful and should just go away now.

**Comment by hamidrezakp** [comment]
> Also, I'll unassign myself as a reviewer — I cannot actually help with the content here and you have to self-organize to make this scale 🙂

Sure, Thank you 👍🏻

**Review by hamidrezakp — COMMENTED** [review]
First off, Thank you for your time taken to translate this part.
The diff is so big that Github can't show it to me, so i will comment the suggestion here for you.

Some of them are related to ZWNJ and some for previous translation.

- [x] "Compile Time Guarantees" => "ضمانت‌های زمان کامپایل"
- [x] "Runtime Guarantees" => "ضمانت‌های زمان اجرا"
- [x] "Scalar Types" => "تایپ‌های عددی"
- [x] "Compound Types" => "تایپ‌های مرکب "
- [x] "Rustdoc" => "مستند نویسی"
- [x] "Type Inference" => "تعیین تایپ ضمنی"
- [x] "Move Semantics" => "مفاهیم جا‌به‌جایی"
- [x] "Moves in Function Calls" => "جابه‌جایی در صدا زدن توابع"
- [x] "Lifetimes in Function Calls" => "طول عمر در فراخوانی‌ توابع"
- [x] "Tuple Structs" => "ساختار‌های تاپل‌ای"
- [ ] "Panics" => "پنیک‌ها"
- [ ] "Generics" => "جنریک‌ها"
- [ ] "Filesystem Hierarchy" => "سلسله‌ مراتب فایل‌سیستم"
- [x] "Tuple Structs" => "ساختار‌های چند‌گانه (Tuple Structs)"

**Comment by moaminsharifi** [comment]
> First off, Thank you for your time taken to translate this part. The diff is so big that Github can't show it to me, so i will comment the suggestion here for you.
> 
> Some of them are related to ZWNJ and some for previous translation.
> 
> * [ ]  "Compile Time Guarantees" => "ضمانت‌های زمان کامپایل"
> * [ ]  "Runtime Guarantees" => "ضمانت‌های زمان اجرا"
> * [ ]  "Scalar Types" => "تایپ‌های عددی"
> * [ ]  "Compound Types" => "تایپ‌های مرکب "
> * [ ]  "Rustdoc" => "مستند نویسی"
> * [ ]  "Type Inference" => "تعیین تایپ ضمنی"
> * [ ]  "Move Semantics" => "مفاهیم جا‌به‌جایی"
> * [ ]  "Moves in Function Calls" => "جابه‌جایی در صدا زدن توابع"
> * [ ]  "Lifetimes in Function Calls" => "طول عمر در فراخوانی‌ توابع"
> * [ ]  "Tuple Structs" => "ساختار‌های تاپل‌ای"
> * [ ]  "Panics" => "پنیک‌ها"
> * [ ]  "Generics" => "جنریک‌ها"
> * [ ]  "Filesystem Hierarchy" => "سلسله‌ مراتب فایل‌سیستم"
> * [ ]  "Tuple Structs" => "ساختار‌های چند‌گانه (Tuple Structs)"

I update most of them as you suggested.
About "Panics" in persian we call it "وحشت زدگی" or "پانیک"
Also "Half-space" fixed in summary part

**Comment by moaminsharifi** [comment]
> Hi @moaminsharifi, in case you didn't notice: `msgmerge` moved a bunch of translations to a kind of "paper bin" at the end of the PO file:
> 
> ```diff
> @@ -21004,3 +19937,150 @@ msgid ""
>  "}\n"
>  "```"
>  msgstr ""
> +
> +#~ msgid "Comparison"
> +#~ msgstr "مقایسه"
> ```
> 
> You should delete them when you think they're no longer useful — the code blocks found there are no longer useful and should just go away now.

I deleted all of them, thanks for mention it.

**Review by hamidrezakp — APPROVED** [review]
LGTM, Thank you

**Comment by mgeisler** [comment]
Just in case you haven't seen it: the translation here also refreshes the messages to include the latest and greatest changes from the English text. I see this because of

```diff
 msgid ""
 msgstr ""
 "Project-Id-Version: Comprehensive Rust 🦀\n"
-"POT-Creation-Date: 2023-08-23\n"
+"POT-Creation-Date: 2023-10-25T14:05:24+03:30\n"
 "PO-Revision-Date: 2023-08-08 21:41+0330\n"
 "Last-Translator: danny <danykhosravi@gmail.com>\n"
 "Language-Team: Persian\n"
```

This explains why the diff is so large, but it's all good.

Just be aware that you shouldn't do a `msgmerge` with every PR — at least not when the translation is still young and incomplete. I recommend working towards a full translation of Day 1 to 3 and then do another refresh then.

Until you refresh, the translation will stay frozen: we `git restore` the English files back to the timestamp in POT-Creation-Date when publishing and this ensures you have a stable ground to work from.

Another good side-effect of only doing `msgmerge` once in a while is that the next PRs will be smaller: they will only _add_ text instead of shuffling things around like this PR does.

**Pull request merged**
