### PR TITLE
Set the correct element type in vector

### PR DESCRIPTION
**Pull request by TalonsLee**

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
Good fix, thanks!

**Comment by djmitche** [comment]
(Note that we are still waiting on the CLA)

**Comment by mgeisler** [comment]
Hi @TalonsLee, will you be able to sign the CLA for the repository?

**Comment by TalonsLee** [comment]
> Hi @TalonsLee, will you be able to sign the CLA for the repository?

done.

**Comment by djmitche** [comment]
Thanks!

**Pull request merged**
