### PR TITLE
Publish Ukrainian translation to language selector

### LINKED ISSUE #836: Ukrainian translation
Thanks @git-user-cpp for starting this in #835. This issue is to track the translation. Please read the instructions linked in #282, in particular, please read the [translation instructions](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md) and the [style guide](https://github.com/google/comprehensive-rust/blob/main/STYLE.md).

The Rust book has been [translated into Ukrainian](https://github.com/rust-lang-ua/rustbook_ukrainian) and it would be good to use its terminology where possible.

If there are many translators, consider using [this sheet](https://docs.google.com/spreadsheets/d/1-EeAaa_pDkBM1j2mOIv5UXngNOwrq4AH8EO_vIakOYU/template/preview) to coordinate the work. This has been helpful for the Chinese and Japanese translations.

### PR DESCRIPTION
**Pull request by henrif75**
Closes #836

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
The fix `id="ja"` has already landed in another PR, I think, but should merge just fine.

**Review by qwandor — APPROVED** [review]

**Comment by reta** [comment]
Thanks a lot @henrif75 !

**Comment by qwandor** [comment]
This appears to be broken, when I click on the Ukrainian option in the translation menu I get a 404.

**Comment by reta** [comment]
> This appears to be broken, when I click on the Ukrainian option in the translation menu I get a 404.

Confirming that as well, @henrif75 any additional publication / changes are required? Ready to jump in if it is helpful, thank you!

**Comment by qwandor** [comment]
#2189 should fix it I think.

**Pull request merged**
