### PR TITLE
ja: Fix file path to avoid build error

### PR DESCRIPTION
**Pull request by maekawatoshiki**
- This PR fixes a wrong filepath (`configure-*` → `configuring-*`) in the Japanese book.
    - I've encountered an error below when I was building the book in Japanese.

```bash
$ MDBOOK_BOOK__LANGUAGE=ja mdbook build -d book/ja
2024-08-15 21:52:56 [INFO] (mdbook::book): Book building has started
2024-08-15 21:52:57 [INFO] (mdbook::book): Running the exerciser backend
2024-08-15 21:52:57 [INFO] (mdbook::renderer): Invoking the "exerciser" renderer
2024-08-15 21:52:57 [INFO] (mdbook::book): Running the html backend
2024-08-15 21:52:58 [INFO] (mdbook::book): Running the linkcheck backend
2024-08-15 21:52:58 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
error: File not found: ../configure-gnrt-config-toml.md
  ┌─ chromium/adding-third-party-crates/resolving-problems/build-scripts-which-generate-code.md:5:23
  │
5 │ もしファイルが作成されるようになっていたら、[`gnrt_config.toml`](../configure-gnrt-config-toml.md) を変更して、クレートに `build-script-outputs` を追加します。これが推移的依存関係（Chromium コードが直接依存すべきでない依存関係）の場合は、`allow-first-party-usage=false` も追加します。このファイルには、すでにいくつかの例が含まれています。
  │                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File not found: ../configure-gnrt-config-toml.md

Error: One or more incorrect links
2024-08-15 21:52:58 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2024-08-15 21:52:58 [ERROR] (mdbook::utils): Error: Rendering failed
2024-08-15 21:52:58 [ERROR] (mdbook::utils):    Caused By: The "linkcheck" renderer failed
```

### CODE REVIEW

**Comment by keiichiw** [comment]
Thanks @maekawatoshiki for the contribution! 
The change looks good to me.
To merge this PR, could you please review and sign a CLA as requested at https://github.com/google/comprehensive-rust/pull/2285#issuecomment-2291217651? Thanks!

**Comment by maekawatoshiki** [comment]
I've just signed the CLA.

**Review by keiichiw — APPROVED** [review]
Thank you!

**Comment by mgeisler** [comment]
Thanks @maekawatoshiki! If you want, you're very welcome to refresh the Japanese translation: [Refreshing an Existing Translation](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#refreshing-an-existing-translation).

That only takes a few minutes. Afterwards, there are [787 fuzzy and 215 untranslated strings](https://google.github.io/comprehensive-rust/synced-translation-report.html). Updating them is the hard part :smile:

**Pull request merged**
