### PR TITLE
Update Android.bp files

### PR DESCRIPTION
**Pull request by spoloxs**
Solves issue #371

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @spoloxs, thanks for the PR!

Have you been able to test the change? I think we also need to update the instructions for how to copy the binaries now.

**Comment by spoloxs** [comment]
I installing the tools which went perfect without any error but when I ran the `mdbook test` I got the following error:

> 
> 2023-07-03 20:07:25 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/babushka/.cargo/bin/src" directory
> 2023-07-03 20:07:25 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)

I don't know much about the error it's showing but I am trying to figure why is it so...

**Comment by spoloxs** [comment]
I liked the book interface you all have created. I will try to help you all as much I can. It's really amazing

**Comment by mgeisler** [comment]
> I installing the tools which went perfect without any error but when I ran the `mdbook test` I got the following error:
> 
> > 2023-07-03 20:07:25 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/babushka/.cargo/bin/src" directory
> > 2023-07-03 20:07:25 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
> 
> I don't know much about the error it's showing but I am trying to figure why is it so...
> 
> Update: I did `mdbook init` and command `mdbook serve` and `mdbook test` started working

I think the problem here is that you're running `mdbook serve` in the wrong directory. You need to clone this repository first and change to its directory:

```
git clone https://github.com/google/comprehensive-rust/
cd comprehensive-rust
mdbook serve
```

**Comment by spoloxs** [comment]
It worked after `mdbook init` I guess it was missing books data so it was showing that error

**Comment by mgeisler** [comment]
> It worked after `mdbook init` I guess it was missing books data so it was showing that error

Do you see the same content on http://localhost:3000 as on https://google.github.io/comprehensive-rust/ after you run `mdbook serve`? If not, then you're in the wrong directory :slightly_smiling_face:

**Comment by spoloxs** [comment]
Oh it showed some blank pages. I will check it again

**Comment by spoloxs** [comment]
Yes I was using wrong directory sorry for my mistake 😔. Everything looks good.

**Comment by mgeisler** [comment]
> Yes I was using wrong directory sorry for my mistake pensive. Everything looks good.

Many people have had the same problem as you! If you have ideas for how to update the instructions, please send us a PR! :smile:

**Comment by spoloxs** [comment]
Just installing AOSP and will try the android commands to check what needs to be updated

**Comment by spoloxs** [comment]
Can I know how to build the files on a physical mobile device? It's taking along time and a lot of space to build AOSP

**Comment by spoloxs** [comment]
AOSP is taking a lot of space and time. I think I should try it on my physical mobile device. It would take some time for me to solve this. Otherwise if someone helps it would be good.

**Review by randomPoison — APPROVED** [review]
I tested this with a local AOSP checkout and everything still builds after the changes 🎉

**Comment by randomPoison** [comment]
@spoloxs Thanks for the contribution! ❤️

**Pull request merged**
