### PR TITLE
zh_CN: .po refresh and remaining course intro translations

### PR DESCRIPTION
**Pull request by henrif75**
Normalizes .po file and add professional translation to missing entries before day 1.
#324

### CODE REVIEW

**Comment by henrif75** [comment]
There are _fuzzy_ entries that can be checked after this is merged.

**Review by kongy — APPROVED** [review]

**Comment by henrif75** [comment]
Thank you @kongy!

**Comment by mgeisler** [comment]
Hi @henrif75 and @kongy, I think something went wrong here since a lot of translated messages disappeared. Compare these two test runs:

- 1a1a9c85db177aa01e3179ac80fbd6199920cba1, immediately before this PR: [1387 translated messages, 32 fuzzy translations, 972 untranslated messages](https://github.com/google/comprehensive-rust/actions/runs/6350901533/job/17251282938).
- 86cde61f60e333952c2617801a9bee7ddadcae2b, part of his PR: [325 translated messages, 18 fuzzy translations, 4 untranslated messages](https://github.com/google/comprehensive-rust/actions/runs/6355677108/job/17264106522?pr=1242).

I tried checking out 1a1a9c85db177aa01e3179ac80fbd6199920cba1 and ran `msgmerge --update`. There are still 1187 translated messages after this, so the problem is not simply that lots of stuff changes in the English version.

Please take [the old `zh-CN.po` file](https://github.com/google/comprehensive-rust/blob/b3bcaacb7095ab172d43737b95d9ce7788afef1d/po/zh-CN.po) and combine it with the current version using `msgcat` and then run `msgmerge` on the result. That should help restore the old translations that still work.

**Comment by henrif75** [comment]
I agree, it's weird. I guess there was too many PRs at different baselines. I'm going to pull out the open zh-CN PRs and re-merge the translated entries.

**Comment by mgeisler** [comment]
> I agree, it's weird. I guess there was too many PRs at different baselines. I'm going to pull out the open zh-CN PRs and re-merge the translated entries.

Okay, let me know if you run into problems! A quick

```
msgfmt -o /dev/null --statistics po/zh-CN.po
```

should tell you the state of the file after the surgery :slightly_smiling_face:

**Pull request merged**
