### PR TITLE
Filled missing glossary terms with their explanations

### LINKED ISSUE #1466: Fill out the English glossary
We have had a glossary for a few weeks now: https://google.github.io/comprehensive-rust/glossary.html

It is mostly incomplete and we could use help with filling out the definitions.

### PR DESCRIPTION
**Pull request by ANURAGSISODIYAA**
Changes Made
This Pull Request addresses issue #1466  and includes the following changes:
Added Glossary Terms: Filled in missing glossary terms with their respective explanations.

Context
The glossary is a crucial reference for understanding key terms in the project. This PR enhances its completeness and readability by adding missing terms and improving the overall formatting.

Related Issues

Fixes #1466.

### CODE REVIEW

**Review by randomPoison — APPROVED** [review]
These definitions are excellent, thanks for getting these written!

**Comment by randomPoison** [comment]
@mgeisler It looks like the Brazilian Portuguese translation is failing in CI for some reason, even though this PR doesn't seem to touch anything related to the tests that are failing. Any idea what's going on here? I'm not terribly familiar with the translations work.

**Comment by ANURAGSISODIYAA** [comment]
> @mgeisler It looks like the Brazilian Portuguese translation is failing in CI for some reason, even though this PR doesn't seem to touch anything related to the tests that are failing. Any idea what's going on here? I'm not terribly familiar with the translations work.

**Comment by mgeisler** [comment]
> @mgeisler It looks like the Brazilian Portuguese translation is failing in CI for some reason, even though this PR doesn't seem to touch anything related to the tests that are failing. Any idea what's going on here? 

Yes, we had a race between two PRs: #1460, which updated our tooling, and #1467 which updated a translation to the new format. This was fixed in #1472 and I'll simply trigger a rerun of the GH actions.

**Pull request merged**
