### PR TITLE
es: Spanish translation refresh

### LINKED ISSUE #2120: Spanish (es): Catch-up with EN version
Translate remaining messages and review fuzzy translations.
As of 6/5/24, current translation stats are:
```
es.po
3129 translated messages, 450 fuzzy translations, 194 untranslated messages.
```
### Steps:
1. Sync your branch with `main`.
2. Recreate `messages.pot`:
```shell
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' \
  mdbook build -d po
```
3. Merge with the `es.po`:
```shell
msgmerge --update po/es.po po/messages.pot
```
4. Edit the `es.po` file with your favorite PO editor.

### PR DESCRIPTION
**Pull request by carreter**
Fixes #2120.

### CODE REVIEW

**Comment by mgeisler** [comment]
Hey @carreter, this looks nice from a format point of view. I used

```
gh pr diff 2232 | bat -l patch
```

to skim through the diff. I don't know Spanish, so I cannot help with the actual content.

**Comment by mgeisler** [comment]
Since this looks fine from a structure point, I'm happy to merge this if you can resolve the conflicts.

You might need to hand-merge the out-of-date `.po` files, so take a look at the steps here: https://github.com/google/comprehensive-rust/pull/1948#issuecomment-2301415834. The recipe there basically treats each file as a large `(msgid, msgstr)` map and takes the union of the two files. That "trick" might come in handy here or in other PRs.

**Comment by henrif75** [comment]
We probably need to run dprint here

**Comment by henrif75** [comment]
Hi @carreter , were you able to run dprint fmt on the file? If you've done that, would you also convert this PR from draft to ready to review?

**Comment by carreter** [comment]
@henrif75 Done. I'll mark it ready to review but note that many of the entries are still untranslated.

**Comment by deavid** [comment]
I reviewed the Spanish text added on this PR and all seems correct to me.

**Comment by carreter** [comment]
I'll open a stacked PR for further translation work. Still have ~200 entries to go!

**Comment by mgeisler** [comment]
> I'll open a stacked PR for further translation work. Still have ~200 entries to go!

Yay, thanks for the amazing work!

Note that we squash-merge all PRs here — this makes it easier for new contributors since they can just pile on commit after commit in their PR without having to consider how the resulting history looks like. So it's fine to open a new PR with this as a base.

**Comment by mgeisler** [comment]
Oh, sorry about the unrelated format errors... This is #2165 and I still haven't gotten around to debug this in depth.

@carreter, I know you didn't have to sign the CLA, but the bot is no longer happy with the PR... can you sign it?

**Comment by mgeisler** [comment]
> Oh, sorry about the unrelated format errors... This is #2165 and I still haven't gotten around to debug this in depth.

Actually, I didn't look carefully enough: could you revert the changes to the other translations from this PR? I guess there is a version mismatch somewhere between the `msgcat` you have and the one in GitHub's CI (if you look in `dprint.json`, you'll see that we simply run the `.po` files through `msgcat -`).

**Comment by carreter** [comment]
> Actually, I didn't look carefully enough: could you revert the changes to the other translations from this PR? I guess there is a version mismatch somewhere between the `msgcat` you have and the one in GitHub's CI (if you look in `dprint.json`, you'll see that we simply run the `.po` files through `msgcat -`).

On it!

**Comment by carreter** [comment]
CLA is working now and I have reverted the non-Spanish translation changes. @mgeisler let me know if anything else is needed!

**Comment by mgeisler** [comment]
Excellent, great that you got it working! I know from the past that people do need a Google/Gmail account, but it is possible to add non-Gmail addresses to the CLA bot.

**Comment by carreter** [comment]
@mgeisler Can you re-open this? There's still some work to be done.

**Pull request merged**
