### PR TITLE
fr: Refreshing the French translation

### PR DESCRIPTION
**Pull request by AdrienBaudemont**
fr: Refreshing the French translation (running msgmerge, not other change).

### CODE REVIEW

**Comment by AdrienBaudemont** [comment]
> Hi @AdrienBaudemont, could you extract the strings using
> 
> ```
> MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' \
>   mdbook build -d po
> ```
> 
> so that there are no line numbers in the messages? You should be able to update the PR by simply re-extracting the messages and run `msgmerge` again.
> 
> Right now the diff is larger than it has to be:
> 
> ```diff
> -#: src/SUMMARY.md
> +#: src/SUMMARY.md:18 src/SUMMARY.md:47 src/SUMMARY.md:76 src/SUMMARY.md:103
> +#: src/SUMMARY.md:129 src/SUMMARY.md:149 src/SUMMARY.md:167 src/SUMMARY.md:190
> +#: src/SUMMARY.md:213 src/SUMMARY.md:262 src/SUMMARY.md:304 src/SUMMARY.md:355
>  msgid "Welcome"
>  msgstr "Bienvenue"
>  
> -#: src/SUMMARY.md src/hello-world.md src/hello-world/hello-world.md
> +#: src/SUMMARY.md:19 src/SUMMARY.md:24 src/hello-world.md:1
> +#: src/types-and-values/hello-world.md:1
>  #, fuzzy
>  msgid "Hello, World"
>  msgstr "Bonjour le monde!"
>  
> -#: src/SUMMARY.md src/hello-world/what-is-rust.md
> +#: src/SUMMARY.md:20 src/hello-world/what-is-rust.md:1
>  msgid "What is Rust?"
>  msgstr "Qu'est-ce que Rust ?"
> ```
> 
> This requires a recent installation of mdbook-i18n-helpers.

Hello @mgeisler , 
Thank you for your review and your detailed comment!
I had to update multiple things on my end (rust, mdbook, mdbook-i18n-helpers) and I could update the pull request.
Do not hesitate to let me know if other changes are needed, the line numbers should be gone.
Thank you!

**Comment by mgeisler** [comment]
Hi @AdrienBaudemont, looks great now! Let me merge it so you have a new stable base to work from!

When you feel like it, then you're welcome to remove the old "semi-deleted" entries from the end of the file:

```patch
+#, fuzzy
+#~ msgid "`String` a mutable string buffer."
+#~ msgstr "`String` un tampon de chaîne mutable."
+
+#, fuzzy
+#~ msgid "Rust comes with only basic support for writing tests."
+#~ msgstr "Rust a un support intégré pour les tests de documentation :"
+
+#, fuzzy
+#~ msgid ""
+#~ "Add `vendor_available: true` if your AIDL file is used by a binary in the "
+#~ "vendor partition."
+#~ msgstr ""
+#~ "Ajoutez `vendor_available : true` si votre fichier AIDL est utilisé par "
+#~ "un binaire dans le fournisseur cloison."
```

They don't cause any harm, they're just sitting around in case someone wants to refer to them in the future. It's `msgmerge` that puts them there when it notices that a translated entry is no longer used. Translators can then manually delete them as they like.

**Review by mgeisler — APPROVED** [review]
Thanks!

**Comment by AdrienBaudemont** [comment]
@mgeisler Thank you for your review and for the information about the semi-deleted older translation messages! I was not aware of that, I opened another pull request to clean those up (there were quite a few of them indeed).

**Pull request merged**
