### PR TITLE
pt-BR: Refresh .po file after original content updates

### PR DESCRIPTION
**Pull request by henrif75**
Part of pt-BR: Coordinating updates and additional translations #893

### CODE REVIEW

**Comment by mgeisler** [comment]
Hey @henrif75, can I get you to `cargo install mdbook-i18n-helpers` to update to version 0.2.4 which I released just now? That will ensure that the POT-Creation-Date field is updated (instead of being cleared).

**Comment by henrif75** [comment]
I'm changing it to a draft again to address the huge diff.

**Comment by mgeisler** [comment]
> I'm changing it to a draft again to address the huge diff.

With the new `dprint` setup, you should be able to get a smaller diff with a `dprint fmt`.

**Comment by mgeisler** [comment]
Hey folks! Do we still need this PR?

**Pull request closed without merging**
