### PR TITLE
ar: refresh translation

### PR DESCRIPTION
**Pull request by younies**

### CODE REVIEW

**Review by henrif75 — COMMENTED** [review]
Hi @younies,
The `.po` file has a big diff, because the comments with file names have the line number.
Did you try to extract the `messages.pot` file with the granularity parameter set to 0?
```shell
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' \
  mdbook build -d po
```

**Comment by younies** [comment]
> Hi @younies, The `.po` file has a big diff, because the comments with file names have the line number. Did you try to extract the `messages.pot` file with the granularity parameter set to 0?
> 
> ```shell
> MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' \
>   mdbook build -d po
> ```

@henrif75 , yes, I have done this :)

**Comment by henrif75** [comment]
> > Hi @younies, The `.po` file has a big diff, because the comments with file names have the line number. Did you try to extract the `messages.pot` file with the granularity parameter set to 0?
> > ```shell
> > MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' \
> >   mdbook build -d po
> > ```
> 
> @henrif75 , yes, I have done this :)

That's funny. It's not the first time that happens. Can you check one more thing, which version of the gettext tools do you have installed?

For reference, I ran the command and updated the ar.po file (added `.txt` to be able to upload) 
[ar.po.txt](https://github.com/user-attachments/files/16168964/ar.po.txt)

**Comment by younies** [comment]
> eck thi

@henrif75 

interesting, here is my version

```
gettext (GNU gettext-runtime) 0.22.5
Copyright (C) 1995-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
```

**Comment by younies** [comment]
Hi @henrif75,

I have created this PR (https://github.com/google/comprehensive-rust/pull/2216) to show the difference in `gettext` file generation.

I am not sure why there is a big difference.

**Comment by henrif75** [comment]
I noticed that in this last commit the file format is correct, have you done anything differently?

**Review by henrif75 — APPROVED** [review]

**Comment by younies** [comment]
> I noticed that in this last commit the file format is correct, have you done anything differently?

@henrif75 , no , I just copied the file that you have generated.

**Comment by henrif75** [comment]
> > I noticed that in this last commit the file format is correct, have you done anything differently?
> 
> @henrif75 , no , I just copied the file that you have generated.

As a last request, could you check which version of mdbook you're using?
```mdbook --version```
I'll open an issue to investigate what's going on.
Thanks for your patience.

**Comment by carreter** [comment]
FYI, fix for this is now up in a PR: https://github.com/google/mdbook-i18n-helpers/pull/215

**Pull request merged**
