### PR TITLE
n1 should be 5, not 15

### PR DESCRIPTION
**Pull request by n8behavior**

### CODE REVIEW

**Review by mgeisler — APPROVED** [review]
Thanks!

**Comment by mgeisler** [comment]
We can ignore the "Course Schedule Updates" failure, it's not because of your change! It's due to permission in problems as discussed on #1576.

However, if you can sign the CLA, then this is ready to merge.

**Comment by n8behavior** [comment]
Ok, signed the CLA

**Comment by mgeisler** [comment]
Thanks a lot!

**Pull request merged**
