### PR TITLE
fr: Updating French translation file, and a few messages.

### PR DESCRIPTION
**Pull request by yohcop**
Re-generated a new po/messages.pot, and merged into po/fr.po.

Updated a handful of message translations as well, but this small PR is mostly to 'get my feet wet' with the whole process.

Part of #323.

### CODE REVIEW

**Comment by mgeisler** [comment]
Thanks @yohcop! I added a reference to the French translation issue (that way the PR shows up on the issue).

**Comment by yohcop** [comment]
I'm not sure if I did this right. The file is so big, as most line numbers have changed, that github doesn't want to load the diff. Let me know if I should do things differently.

**Review by sakex — APPROVED** [review]
This is a huge CL, we can merge it like this for now. I will have a longer look on this next week

**Comment by sakex** [comment]
Also, it doesn't let me add my review comments for some reason

**Comment by mgeisler** [comment]
> I'm not sure if I did this right. The file is so big, as most line numbers have changed, that github doesn't want to load the diff. Let me know if I should do things differently.

You did it right! The problem is that `msgmerge` formats the PO file differently than our `mdbook-xgettext` plugin. I should fix that so I filed https://github.com/google/mdbook-i18n-helpers/issues/32 for it.

**Comment by mgeisler** [comment]
I merged this, thanks for looking it over!

@sakex, you should generally merge PRs when approving them since most people won't have write access to the repository.

**Pull request merged**
