### PR TITLE
Divided Array and tuples

### PR DESCRIPTION
**Pull request by mani-chand**
#1824 PR Changes

### CODE REVIEW

**Review by djmitche — CHANGES_REQUESTED** [review]
This looks great! I think it's a good idea to make this two top-level slides, rather than a sub-slide.

The only thing I'd request to change is the order of the two slides. Tuples come first right now, but the speaker notes start with "Like arrays .." I think it would be easier to understand if the order were swapped, with arrays coming first. I don't think any other changes are required to the content, other than swapping the order.

**Comment by mani-chand** [comment]
Hello @djmitche , I think now you merge the PR.

**Review by djmitche — APPROVED** [review]
Great -- thank you again!

**Comment by mani-chand** [comment]
> Great -- thank you again!

No need to thank me . I just love doing technical things . I would like you to thank for giving me ideas, helping ad suggestions.

**Pull request merged**
