### PR TITLE
translate chaptor 1-13 & 57-60 to chinese-cn version

### PR DESCRIPTION
**Pull request by SketchK**
translate chaptor 1-13 & 57-60 to Simplified Chinese

### CODE REVIEW

**Comment by SketchK** [comment]
@anlunx @kongy @NoahDragon @emmali01 
Anyone can review the PR? 
I will update & finish all the book in Chinese version in One Month!

**Comment by henrif75** [comment]
> @anlunx @kongy @NoahDragon @emmali01 Anyone can review the PR? I will update & finish all the book in Chinese version in One Month!

Hi @SketchK , we have several PRs to translate most of the remaining course. Perhaps you could review them or you could continue your translation from the Android section and onwards. Please let me know, thanks for your contributions!

**Comment by SketchK** [comment]
@henrif75 Thank you for you reply!
I just want to finish Chinese version as soon as possible. 
I think review or continue my translation is both ok!
In order to reduce the duplication of work, I think it may be more reasonable to review all the existing Chinese translations first, and I am willing to join in if necessary

> By the way, I translate swift programming language to Chinese before , and this version is recommend by apple in [swift.doc](https://www.swift.org/documentation/)

**Comment by henrif75** [comment]
> @henrif75 Thank you for you reply! I just want to finish Chinese version as soon as possible. I think review or continue my translation is both ok! In order to reduce the duplication of work, I think it may be more reasonable to review all the existing Chinese translations first, and I am willing to join in if necessary
> 
> > By the way, I translate swift programming language to Chinese before , and this version is recommend by apple in [swift.doc](https://www.swift.org/documentation/)

You can send a PR to add yourself to the CODEOWNERS file, if you want.

**Review by kongy — APPROVED** [review]

**Comment by SketchK** [comment]
> > @henrif75 Thank you for you reply! I just want to finish Chinese version as soon as possible. I think review or continue my translation is both ok! In order to reduce the duplication of work, I think it may be more reasonable to review all the existing Chinese translations first, and I am willing to join in if necessary
> > > By the way, I translate swift programming language to Chinese before , and this version is recommend by apple in [swift.doc](https://www.swift.org/documentation/)
> 
> You can send a PR to add yourself to the CODEOWNERS file, if you want.

Hi, @henrif75 I think this is a good idea, but where can i find the codeowners file? thank you

**Comment by henrif75** [comment]
> > > @henrif75 Thank you for you reply! I just want to finish Chinese version as soon as possible. I think review or continue my translation is both ok! In order to reduce the duplication of work, I think it may be more reasonable to review all the existing Chinese translations first, and I am willing to join in if necessary
> > > > By the way, I translate swift programming language to Chinese before , and this version is recommend by apple in [swift.doc](https://www.swift.org/documentation/)
> > 
> > 
> > You can send a PR to add yourself to the CODEOWNERS file, if you want.
> 
> Hi, @henrif75 I think this is a good idea, but where can i find the codeowners file? thank you

Hey @SketchK, you can find more information here: https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#reviewing-translations

**Comment by SketchK** [comment]
> > > > @henrif75 Thank you for you reply! I just want to finish Chinese version as soon as possible. I think review or continue my translation is both ok! In order to reduce the duplication of work, I think it may be more reasonable to review all the existing Chinese translations first, and I am willing to join in if necessary
> > > > > By the way, I translate swift programming language to Chinese before , and this version is recommend by apple in [swift.doc](https://www.swift.org/documentation/)
> > > 
> > > 
> > > You can send a PR to add yourself to the CODEOWNERS file, if you want.
> > 
> > 
> > Hi, @henrif75 I think this is a good idea, but where can i find the codeowners file? thank you
> 
> Hey @SketchK, you can find more information here: https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md#reviewing-translations

Hi @henrif75 ,this is my #1309 , hope you will approve it!

**Pull request closed without merging**
