### PR TITLE
Update other-resources.md

### PR DESCRIPTION
**Pull request by VENCYR**
Added Rust Primer and CodeCrafters

### CODE REVIEW

**Review by randomPoison — APPROVED** [review]
Looks good to me! These seem like useful resources to have listed 😁

Please sign the Google Contributor License Agreement so that we can merge this PR.

**Comment by VENCYR** [comment]
> Looks good to me! These seem like useful resources to have listed 😁
> 
> Please sign the Google Contributor License Agreement so that we can merge this PR.

Done!

**Comment by randomPoison** [comment]
@VENCYR thank you for your contribution! ❤️

**Comment by randomPoison** [comment]
@adwsingh ah, thanks for bringing that to my attention! I had done a cursory look at CodeCrafters and didn't notice that. I'll get this reverted.

**Pull request merged**
