### PR TITLE
On mac use Cmd-Enter to run the code blocks

### PR DESCRIPTION
**Pull request by rbehjati**

### CODE REVIEW

**Comment by mgeisler** [comment]
Can you check if you can simply add another binding instead of changing the current one? It would be nice to be consistent with other `mdbook` projects and so I would prefer to keep the current binding.

**Review by mgeisler — CHANGES_REQUESTED** [review]
Please also update the page about keyboard shortcuts.

**Comment by rbehjati** [comment]
> Can you check if you can simply add another binding instead of changing the current one? It would be nice to be consistent with other `mdbook` projects and so I would prefer to keep the current binding.

I agree. Multiple bindings would have been nice, but I could not find a way to do this. 
Also, it looks like most people have re-mappings that makes `Ctrl-Enter` work on mac. So I am going to close this :)

**Comment by mgeisler** [comment]
> I agree. Multiple bindings would have been nice, but I could not find a way to do this.
> Also, it looks like most people have re-mappings that makes `Ctrl-Enter` work on mac. So I am going to close this :)

Okay! Thanks for looking!

**Pull request closed without merging**
