### PR TITLE
uk: Create Ukrainian translation

### PR DESCRIPTION
**Pull request by git-user-cpp**
Added Ukrainian translation

Part of #836 .

### CODE REVIEW

**Comment by git-user-cpp** [comment]
Hello, I added Ukrainian translation. Could you please make me a reviewer of new commits for this file?

**Comment by mgeisler** [comment]
Hi @git-user-cpp, thanks for creating the file!

Now that the tests ran, there seems to be a little syntax error:

```
msgfmt --statistics -o /dev/null po/ua.po
po/ua.po:1783: keyword "stable" unknown
po/ua.po:1783: syntax error
msgfmt: found 2 fatal errors
Error: Process completed with exit code 1.
```

> Hello, I added Ukrainian translation. Could you please make me a reviewer of new commits for this file?

Certainly — you should actually do this yourself by adding your username to the `.github/CODEOWNERS` file. Then new PRs will be sent your way automatically.

**Comment by git-user-cpp** [comment]
A syntax error was fixed

**Comment by mgeisler** [comment]
> Thank you for your response! A syntax error was fixed

Great! I've reached out internally to find some Googlers who can help with the translation and with reviews.

For now, can you rename the file to `uk.po`? That's the [ISO 639-1 language code for Ukrainian](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). From searching a bit, it seems that "UA" is the [ISO 3166 country code](https://en.wikipedia.org/wiki/ISO_3166), similar to how Danish (my language) is in a ` da.po` file while the country has `.dk` as it's TLD.

**Comment by git-user-cpp** [comment]
thanks for the information! Sorry, I didn't know that it should be uk.po :sweat_smile:

**Comment by mgeisler** [comment]
> Sorry, I didn't know that it should be uk.po sweat_smile

Me neither :smile: It looks like United Kingdom to me, but apparently not... so today I learnt something!

**Comment by git-user-cpp** [comment]
I thought it was the United Kingdom too :smiley:

**Comment by mgeisler** [comment]
Hi @git-user-cpp, I've found at least one person who will be happy to help here: @dyeroshenko. He will do a review of your PR as soon as possible.

**Comment by git-user-cpp** [comment]
Thanks a million! :smiley:

**Review by dyeroshenko — APPROVED** [review]
LGTM!

**Pull request merged**
