### PR TITLE
zh-CN: Day 1 Translations

### PR DESCRIPTION
**Pull request by henrif75**
Professional translations for missing day 1 entries #324

### CODE REVIEW

**Comment by henrif75** [comment]
This is a new attempt, after fixing the original .po file.

**Comment by SketchK** [comment]
Hi @henrif75 I made my id into the CODEOWNERS file, but I still can't review this pr?
what should i do next ?

**Comment by henrif75** [comment]
> Hi @henrif75 I made my id into the CODEOWNERS file, but I still can't review this pr? what should i do next ?

Hi @SketchK You should have received an invitation email from GitHub. Once you accept it, you should be able to review and approve PRs.
Thanks!

**Review by SketchK — APPROVED** [review]

**Comment by henrif75** [comment]
Thanks!

**Pull request merged**
