### PR TITLE
Add a page which mentions the translations

### PR DESCRIPTION
**Pull request by mgeisler**
This is to help people discover the language picker.

### CODE REVIEW

**Comment by mgeisler** [comment]
@rastringer, @hugojacob: I would be happy to add your names to the page to highlight your contributions. Do you think that would be okay?

@jiyongp and @jooyunghan, what do you think?

**Comment by jooyunghan** [comment]
I'm okay

**Comment by mgeisler** [comment]
> I'm okay

Okay, I've added GitHub usernames now to help spread the credit! I think that'll be good overall since we want to thank people for the huge amount of work there is in a translation.

**Comment by rastringer** [comment]
Certainly, thank you

**Review by rastringer — APPROVED** [review]

**Comment by jiyongp** [comment]
Sure. Thanks!

**Pull request merged**
