### PR TITLE
zh-CN: format translation file and add "borrow errors" translation

### PR DESCRIPTION
**Pull request by zer0fire**
The po file has been refreshed, and when I use `msgmerg` it update format auto automatically.
And add a translation, range: L506-L508.

lcqSi3zaoZ

### CODE REVIEW

**Comment by zer0fire** [comment]
These pushed because I need to modify my email address and pass the CLA check

**Comment by mgeisler** [comment]
Hi @zer0fire, thanks for refreshing the translation.

Can I get you to `cargo install mdbook-i18n-helpers` again to ensure you have the latest version? It should be version 0.3.3 right now.

Then please use the refresh command with the `granularity` set to `0` to ensure that there are no line numbers in the PO file. Right now, I see extra line numbers being added:

```diff
% gh pr diff 2100 | bat -l patch | head -25
diff --git a/po/zh-CN.po b/po/zh-CN.po
index b2ab0af8a8d..49e7f96a3b5 100644
--- a/po/zh-CN.po
+++ b/po/zh-CN.po
@@ -1,7 +1,7 @@
 msgid ""
 msgstr ""
 "Project-Id-Version: Comprehensive Rust 🦀\n"
-"POT-Creation-Date: 2024-02-08T15:26:53+08:00\n"
+"POT-Creation-Date: 2024-05-27T15:33:29+08:00\n"
 "PO-Revision-Date: \n"
 "Last-Translator: \n"
 "Language-Team: Language zh-Hans\n"
@@ -10,1167 +10,1310 @@ msgstr ""
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Poedit 3.4.2\n"
+"X-Generator: Poedit 3.4.4\n"
 
-#: src/SUMMARY.md src/index.md
+#: src/SUMMARY.md:3 src/index.md:1
 msgid "Welcome to Comprehensive Rust 🦀"
 msgstr "欢迎来到 Comprehensive Rust 🦀"
```

You can simply re-extract the messages to `messages.pot` and then `msgmerge` again. That should fix things.

**Comment by zer0fire** [comment]
> Hi @zer0fire, thanks for refreshing the translation.
> 
> Can I get you to `cargo install mdbook-i18n-helpers` again to ensure you have the latest version? It should be version 0.3.3 right now.
> 
> Then please use the refresh command with the `granularity` set to `0` to ensure that there are no line numbers in the PO file. Right now, I see extra line numbers being added:
> 
> ```diff
> % gh pr diff 2100 | bat -l patch | head -25
> diff --git a/po/zh-CN.po b/po/zh-CN.po
> index b2ab0af8a8d..49e7f96a3b5 100644
> --- a/po/zh-CN.po
> +++ b/po/zh-CN.po
> @@ -1,7 +1,7 @@
>  msgid ""
>  msgstr ""
>  "Project-Id-Version: Comprehensive Rust 🦀\n"
> -"POT-Creation-Date: 2024-02-08T15:26:53+08:00\n"
> +"POT-Creation-Date: 2024-05-27T15:33:29+08:00\n"
>  "PO-Revision-Date: \n"
>  "Last-Translator: \n"
>  "Language-Team: Language zh-Hans\n"
> @@ -10,1167 +10,1310 @@ msgstr ""
>  "Content-Type: text/plain; charset=UTF-8\n"
>  "Content-Transfer-Encoding: 8bit\n"
>  "Plural-Forms: nplurals=1; plural=0;\n"
> -"X-Generator: Poedit 3.4.2\n"
> +"X-Generator: Poedit 3.4.4\n"
>  
> -#: src/SUMMARY.md src/index.md
> +#: src/SUMMARY.md:3 src/index.md:1
>  msgid "Welcome to Comprehensive Rust 🦀"
>  msgstr "欢迎来到 Comprehensive Rust 🦀"
> ```
> 
> You can simply re-extract the messages to `messages.pot` and then `msgmerge` again. That should fix things.

Alreay fixed, thanks for your reply.
image

But I also noticed after I run these command, it is also have some other sign, I don't know how to fix. Do these sign affect something?
image

**Comment by mgeisler** [comment]
> Do these signs affect something?

Yes, they make the output of `git diff` much bigger than it should be — which makes it harder to see what is going on (it's already pretty hard because the file is so large :smile:).

Can you double-check how the messages look in your `messages.pot` file? They should not have the line numbers (the `:1` part you saw).

Also, you need to install the `mdbook-course` preprocessor. The steps are in [Building](https://github.com/google/comprehensive-rust/blob/main/README.md#building).

**Comment by wangmengCC** [comment]
I alreay install `mdbook-course` and any other dependencies, but I have no idea about how to fixed these line numbers. 😂

image
image

And this is my messages.pot, I also see these numbers.
image

**Comment by henrif75** [comment]
> I alreay install `mdbook-course` and any other dependencies, but I have no idea about how to fixed these line numbers. 😂
> 
> image image
> 
> And this is my messages.pot, I also see these numbers. image

You'll need to regenerate the messages.pot with the correct parameter `granularity`:
```
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' \
  mdbook build -d po
```
After that you can use the `msgmerge` again.

**Comment by zer0fire** [comment]
> > I alreay install `mdbook-course` and any other dependencies, but I have no idea about how to fixed these line numbers. 😂
> > image image
> > And this is my messages.pot, I also see these numbers. image
> 
> You'll need to regenerate the messages.pot with the correct parameter `granularity`:
> 
> ```
> MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' \
>   mdbook build -d po
> ```
> 
> After that you can use the `msgmerge` again.

I alreay use this command but it also has these line numbers.

image
image

**Comment by henrif75** [comment]
@zer0fire Wild guess, can you check whether you have the latest version of the [gettext](https://www.gnu.org/software/gettext/) lib installed?

**Comment by zer0fire** [comment]
> @zer0fire Wild guess, can you check whether you have the latest version of the [gettext](https://www.gnu.org/software/gettext/) lib installed? Check our [How to Contribute](https://github.com/google/comprehensive-rust/blob/main/CONTRIBUTING.md) page. Thanks.

I appreciate your help, I have already updated libraries to the latest version. but it looks like it still doesn't work. 😭
Maybe my `xgettext` settings were wrong?

image

image

**Comment by henrif75** [comment]
@zer0fire I created a new codespace and I was able to reproduce the problem because it used an older version of gettext.
I'm wondering if, somehow, the command is invoking a different binary from the library you've installed via brew.
If you type `gettext --version` from the root directory of your project, what do you get?

**Comment by zer0fire** [comment]
> @zer0fire I created a new codespace and I was able to reproduce the problem because it used an older version of gettext. I'm wondering if, somehow, the command is invoking a different binary from the library you've installed via brew. If you type `gettext --version` from the root directory of your project, what do you get?

This is my result, Accroding to the document it is the latest release (0.22.5)

image

**Comment by henrif75** [comment]
> > @zer0fire I created a new codespace and I was able to reproduce the problem because it used an older version of gettext. I'm wondering if, somehow, the command is invoking a different binary from the library you've installed via brew. If you type `gettext --version` from the root directory of your project, what do you get?
> 
> This is my result, Accroding to the document it is the latest release (0.22.5)
> 
> image

@mgeisler Would you have any other idea on why is this happening?

**Pull request closed without merging**
