### PR TITLE
KO: Refreshes `ko.po` (#262) to v.2 without adding translations.

### PR DESCRIPTION
**Pull request by henrif75**
Updates the `ko.po` with the v.2 English strings, without adding new translations. 
It will set the base to merge the professional translations later (#1463).

To avoid disruptions on the live KO version, this will be merged into a new branch (ko-v2), until all PRs are reviewed.

### CODE REVIEW

**Comment by jiyongp** [comment]
Hi,

I checked out the two commits locally and saw that most (I didn't count, but it felt like 99%) of the korean translations are gone. The translations for simple tokens like "Welcome to Day 1" are gone. Is that expected?

**Comment by henrif75** [comment]
I'm sending the PRs with the new translations provided by the localization team.

**Comment by henrif75** [comment]
On a second thought, I think you're right, there's something wrong here 🤦 Let me restart everything again.

**Comment by jiyongp** [comment]
No worries. The second series of PRs look good. I will review them today or tomorrow.

**Pull request merged**
