### PR TITLE
[fa] day 1

### PR DESCRIPTION
**Pull request by alix1383**
https://github.com/google/comprehensive-rust/pull/2238 CLA fix

### CODE REVIEW

**Comment by alerque** [comment]
Please don't close and re-open PRs. It makes it really difficult to keep track of all the review activity. Keep working on the same branch and applying fixes to it until it is ready to me merged, closing and re-opening is an anti-pattern. Thanks.

**Comment by DannyRavi** [comment]
> Please don't close and re-open PRs. It makes it really difficult to keep track of all the review activity. Keep working on the same branch and applying fixes to it until it is ready to me merged, closing and re-opening is an anti-pattern. Thanks.

Hi @alerque 
I suggested @alix1383  to close the previous request and commit and push it once more
Because he had an apparently unsolvable problem with CLA (because he commit with different email) and I didn't know what to do.
We will definitely consider what you mentioned in the future.
thanks.

**Comment by alerque** [comment]
You can change the email of a commit by amending the commit and force pushing it. Checkout the branch, use `git commit --amend --author "Name <email>"` to change the author of the previous commit (or `git rebase` with breaks to amend multiple commits).

**Review by DannyRavi — APPROVED** [review]

**Comment by DannyRavi** [comment]
Hi @alerque 
Unfortunately, some tests related to other languages ​​do not pass
If only fa.po file is changed and committed
What do you suggest?

**Comment by jond01** [comment]
> Hi @alerque Unfortunately, some tests related to other languages ​​do not pass If only fa.po file is changed and committed What do you suggest?

The issue is #2247. It is fixed by #2250, waiting to be approved and merged.

However, thanks to this issue, we note that the links in Persian ("fa") are correct 😄 
@alix1383, could you please add "fa" to the list in L152:
https://github.com/google/comprehensive-rust/blob/ad9b41cd6cba0b87a2560a155fc5afff1f41713d/.github/workflows/build.yml#L150-L152

**Comment by alix1383** [comment]
@jond01 
https://github.com/google/comprehensive-rust/pull/2252/commits/24366473bb6f9c0695578491c86f67c75a0768d7

Done

**Pull request merged**
