### PR TITLE
bn: Fixed and removed some translations.

### PR DESCRIPTION
**Pull request by raselmandol**
Previously, there were multiple changes made simultaneously by me, resulting in improper translations. I have removed some translations and fixed other translations as instruction. From now I will make smaller changes as it will be easy to review.

### CODE REVIEW

**Review by sudiptachatterjee — APPROVED** [review]
These are easier to understand - thank you

**Comment by mirwasi** [comment]
@raselmandol, could you please resolve the conflicts? Let me know if I can help with this.

**Comment by raselmandol** [comment]
> @raselmandol, could you please resolve the conflicts? Let me know if I can help with this.

@mirwasi can you check now? I have resolved the conflicts.

**Comment by mirwasi** [comment]
Done!

**Pull request merged**
